# Generated by Django 3.1.6 on 2021-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_psicometrico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='active',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
