# Generated by Django 2.2.4 on 2019-10-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='experts', to='participant_section.Participant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gerontologist',
            fields=[
                ('expert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experts_section.Expert')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('experts_section.expert',),
        ),
        migrations.AddField(
            model_name='expert',
            name='expertises',
            field=models.ManyToManyField(blank=True, related_name='experts', to='experts_section.Expertise'),
        ),
    ]
