# Generated by Django 2.2.4 on 2019-09-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerontologist',
            fields=[
                ('expert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experts_section.Expert')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('experts_section.expert',),
        ),
    ]
