# Generated by Django 2.2.4 on 2019-10-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerontologist',
            name='expert',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='experts_section.Expert', verbose_name='Especialista'),
        ),
    ]
