# Generated by Django 2.2.6 on 2020-10-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='accesLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplaName', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='experts_section.Expert')),
                ('orientando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientando', to='experts_section.Expert')),
            ],
        ),
    ]
