# Generated by Django 2.2.6 on 2020-10-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0002_auto_20201023_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientador',
            name='duplaName',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='orientando',
        ),
        migrations.AddField(
            model_name='orientador',
            name='dupla_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='orientador',
            name='dupla_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orientador',
            name='orientando_email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orientador',
            name='orientando_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_orientando', to='experts_section.Expert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orientador',
            name='orientando_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_orientador', to='experts_section.Expert'),
        ),
    ]
