# Generated by Django 3.0.7 on 2020-10-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0003_auto_20201026_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientador',
            name='orientador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='orientando_id',
            field=models.IntegerField(default=0),
        ),
    ]
