# Generated by Django 3.0.7 on 2020-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0004_auto_20201026_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientador',
            name='dupla_email',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
