# Generated by Django 3.0.7 on 2020-10-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0005_auto_20201026_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientador',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador_expert', to='experts_section.Expert'),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='orientando_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientando_expert', to='experts_section.Expert'),
        ),
    ]
