# Generated by Django 2.2.6 on 2020-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0006_auto_20201027_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientador',
            name='qtdPages',
            field=models.IntegerField(default=0),
        ),
    ]
