# Generated by Django 2.2.6 on 2020-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0003_auto_20200925_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageusp',
            options={'ordering': ['id'], 'verbose_name': 'PageUsp', 'verbose_name_plural': 'PageUsp'},
        ),
        migrations.RenameField(
            model_name='functionaldisabilityusp',
            old_name='q27UseTelephone',
            new_name='q27_UseTelephone',
        ),
        migrations.RenameField(
            model_name='functionaldisabilityusp',
            old_name='q29TakeShower',
            new_name='q29_TakeShower',
        ),
        migrations.AddField(
            model_name='cardiovascularfactorsusp',
            name='q37_hypertension_unknow',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='34. O(a) senhor(a) tem hipertensão arterial descontrolada? [Pontuar como sim quando PA auto referida for                    superior a 140/90 mmHg ou caso o(a) idoso(a) não saiba informar.]'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactorsusp',
            name='q38_uncontrolled_diabetes_unknow',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='34. O(a) senhor(a) tem hipertensão arterial descontrolada? [Pontuar como sim quando PA auto referida for                    superior a 140/90 mmHg ou caso o(a) idoso(a) não saiba informar.]'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactorsusp',
            name='q39_cholesterol_unknow',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='34. O(a) senhor(a) tem hipertensão arterial descontrolada? [Pontuar como sim quando PA auto referida for                    superior a 140/90 mmHg ou caso o(a) idoso(a) não saiba informar.]'),
        ),
        migrations.AlterField(
            model_name='pageusp',
            name='interviewed',
            field=models.CharField(choices=[['Participante', 'Participante'], ['Cuidador Formal', 'Cuidador Formal'], ['Familiar', 'Familiar']], max_length=30, verbose_name='Pessoa entrevistada:'),
        ),
        migrations.AlterField(
            model_name='pageusp',
            name='interviewer',
            field=models.CharField(max_length=50, verbose_name='Nome do Entrevistador:'),
        ),
    ]
