# Generated by Django 2.2.6 on 2020-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0004_auto_20201005_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusp',
            name='end_time',
            field=models.CharField(max_length=8, null=True, verbose_name='Hora do Término: '),
        ),
        migrations.AlterField(
            model_name='pageusp',
            name='start_time',
            field=models.CharField(max_length=8, null=True, verbose_name='Hora do início da avaliação: '),
        ),
    ]
