# Generated by Django 2.2.6 on 2020-10-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0005_auto_20201007_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malnutritionusp',
            name='height',
        ),
        migrations.RemoveField(
            model_name='malnutritionusp',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='malnutritionusp',
            name='weight',
        ),
    ]
