# Generated by Django 2.2.6 on 2020-10-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0007_auto_20201007_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionaldisabilityusp',
            old_name='q27_UseTelephone',
            new_name='q27_useTelephone',
        ),
        migrations.RenameField(
            model_name='functionaldisabilityusp',
            old_name='q29_TakeShower',
            new_name='q29_takeShower',
        ),
    ]
