# Generated by Django 2.2.6 on 2020-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0008_auto_20201008_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_01', models.CharField(blank=True, max_length=30, null=True)),
                ('q_02', models.CharField(blank=True, max_length=30, null=True)),
                ('q_03', models.CharField(blank=True, max_length=30, null=True)),
                ('q_04', models.CharField(blank=True, max_length=30, null=True)),
                ('q_05', models.CharField(blank=True, max_length=30, null=True)),
                ('q_06', models.CharField(blank=True, max_length=30, null=True)),
                ('q_07', models.CharField(blank=True, max_length=30, null=True)),
                ('q_08', models.CharField(blank=True, max_length=30, null=True)),
                ('q_09', models.CharField(blank=True, max_length=30, null=True)),
                ('q_10', models.CharField(blank=True, max_length=30, null=True)),
                ('q_11', models.CharField(blank=True, max_length=30, null=True)),
                ('q_12', models.CharField(blank=True, max_length=30, null=True)),
                ('q_13', models.CharField(blank=True, max_length=30, null=True)),
                ('q_14', models.CharField(blank=True, max_length=30, null=True)),
                ('q_15', models.CharField(blank=True, max_length=30, null=True)),
                ('q_16', models.CharField(blank=True, max_length=30, null=True)),
                ('q_17', models.CharField(blank=True, max_length=30, null=True)),
                ('q_18', models.CharField(blank=True, max_length=30, null=True)),
                ('q_19', models.CharField(blank=True, max_length=30, null=True)),
                ('q_20', models.CharField(blank=True, max_length=30, null=True)),
                ('q_21', models.CharField(blank=True, max_length=30, null=True)),
                ('q_22', models.CharField(blank=True, max_length=30, null=True)),
                ('q_23', models.CharField(blank=True, max_length=30, null=True)),
                ('q_24', models.CharField(blank=True, max_length=30, null=True)),
                ('q_25', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='biologicalaspectsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Sobre o Bloco Biológico'),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='multidisciplinarydomainusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Sobre o Bloco Multidimensional'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspectsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre o bloco Psicológico'),
        ),
        migrations.AlterField(
            model_name='sensorydeficitusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='socialaspectsusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Sobre o Bloco Social'),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
