# Generated by Django 2.2.6 on 2021-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0011_auto_20201204_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageusp',
            name='recommendedActivities',
        ),
        migrations.RemoveField(
            model_name='pageusp',
            name='recommendedActivitiesOffers',
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q44_diseases_last_5_years_l_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='l)Outra?'),
        ),
    ]
