# Generated by Django 2.2.6 on 2021-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0012_auto_20210106_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d33_lost_weight_no_reason_amount',
            field=models.CharField(choices=[['Não', 'Não'], ['Não sabe', 'Não sabe'], ['Mais de 3 KG', 'Mais de 3 Kg'], ['Entre 1 e 3 KG', 'Entre 1 e 3 KG']], default='N', max_length=30, verbose_name='33. O(A) senhor(a) tem histórico familiar (1º grau) de DCV (infarto, derrama e/ou angina) ?'),
        ),
    ]
