# Generated by Django 2.2.6 on 2021-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_usp_section', '0013_auto_20210110_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q36_dcv_familiar_history',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q37_hypertension',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q37_hypertension_unknow',
            field=models.CharField(blank=True, choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q38_uncontrolled_diabetes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q38_uncontrolled_diabetes_unknow',
            field=models.CharField(blank=True, choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q39_cholesterol',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q39_cholesterol_unknow',
            field=models.CharField(blank=True, choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q40_smoker',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q41_alcohol_Ingested_last_week',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q41_alcohol_Ingested_last_week_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q41_drink_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q42_practice_exercises',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q42_practice_exercises_regularly',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q42_practise_exercises_frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q42_practise_exercises_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactorsusp',
            name='q43_bmi_obesity',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q1_memory_good_like_others',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q2_three_words',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q3_animals',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q4_three_words',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q5_three_commands',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cognitiondeficitusp',
            name='q6_clock',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='q15_satisfied_with_life',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='q16_frequently_sad',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='q17_stopped_doing_things',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='q18_fear_bad_things_happen',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='depressionusp',
            name='q19_impatient_disquiet',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q72_estable_furniture',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q73_loose_objects_carpets',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q74_slippery_floor',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q75_non_slippery_carpet',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q76_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q77_lighted_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q78_handrail_on_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q79_get_on_stool',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q80_turn_lights_on',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q81_safe_shoes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q82_manicure_sidewalks',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q83_public_transport_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q84_commerce_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q85_ease_plasewalking',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q86_fun_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='environmentalproblemsusp',
            name='q87_safety',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q100_behavior_risk',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q101_inactivity',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q102_prior_ave',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q103_psychotropic_medications_use',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q104_has_diseases',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q88_amount_falls_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q88_falls_last_year',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q89_fractures_due_to_falls',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q89_fractures_due_to_falls_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q90_falls_activity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q91_strength_mmii',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q92_equilibrium',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q93_walking_aid_device',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q94_older_than75',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q95_female',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q96_cognitive_alterations',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q97_av_ds_commitment',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q98_visual_deficit',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='fallsusp',
            name='q99_domestic_risks',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q24_to_shop',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q25_use_transport',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q26_to_cook',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q27_useTelephone',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q28_dress_up',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='functionaldisabilityusp',
            name='q29_takeShower',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_brothers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_father',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_gran_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_great_gran_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_mother',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q55_spouse',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q56_meet_family_friends',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q57_participate_family_decisions',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q58_satisfied_family_relationship',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q59_helped_if_need_money',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q60_someone_helps_if_need',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q61_someone_to_have_fun',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q62_participate_social_events',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='lowsocialsupportusp',
            name='q63_regulary_healt_services',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d30_difficulty_chewing',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d31_less3_meal_daily',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d32_decreases_amount_food',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d33_lost_weight_no_reason',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d33_lost_weight_no_reason_amount',
            field=models.CharField(default='N', max_length=30),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='d34_stress_illness_hospitalization',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='malnutritionusp',
            name='q35_bmi_less22',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q45_health_problems_h_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='h)Outro?'),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q46_medicines_polypharmacy',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q47_know_medicines',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q48_medicines_increase',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q49_medicine_medical_precribed',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q50_medicine_medical_advice',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q51_already_stopped_medicines',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q52_self_medication',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q53_inappropriate_medication',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='misusemedicationsusp',
            name='q54_risk_adverse_reaction',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q10_worried',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q11_sex_life',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q12_little_to_do',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q13_physical_weakness',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q14_better_die',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q7_age_self_perception',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q7_age_self_perception_analyze',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q7_age_self_perception_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q8_good_health',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='negativeattitudesagingusp',
            name='q9_more_neg_pos',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorydeficitusp',
            name='q20_vision_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorydeficitusp',
            name='q21_hearing_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorydeficitusp',
            name='q22_taste_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorydeficitusp',
            name='q23_do_activities_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q64_afraid_close_person',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q65_feels_abandoned',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q66_forced',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q67_assauteld',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q68_in_need',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q69_someone_used_money',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q70_touched_without_permission',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='violenceusp',
            name='q71_dont_take_care_health',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
    ]
