# Generated by Django 2.2.6 on 2020-02-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75)),
                ('number', models.IntegerField()),
                ('district', models.CharField(max_length=40)),
                ('cep', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('communication', models.CharField(max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='institution_section.Address')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('communication', models.CharField(max_length=50)),
                ('parking', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='institution_section.Address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='institution_section.Institution')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('communication', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('professional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Professional')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='institution_section.Institution')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='institution_section.Location')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.professional',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('professional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Professional')),
                ('formation', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.professional',),
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('professional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Professional')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.professional',),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('schedule', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre_goals', models.CharField(max_length=1)),
                ('ambience', models.CharField(max_length=1)),
                ('active_aging', models.CharField(max_length=1)),
                ('motivation', models.TextField()),
                ('people_class', models.IntegerField()),
                ('loe_income', models.CharField(max_length=1)),
                ('partnership', models.TextField()),
                ('home_care', models.CharField(max_length=1)),
                ('requisites', models.TextField()),
                ('activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities_section.Activity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Location')),
                ('contact', models.ManyToManyField(to='institution_section.Contact')),
                ('instructor', models.ManyToManyField(to='institution_section.Instructor')),
                ('responsible', models.ManyToManyField(to='institution_section.Responsible')),
            ],
        ),
    ]
