# Generated by Django 2.2.6 on 2019-11-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities_section', '0001_initial'),
        ('institution_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('schedule', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre_goals', models.CharField(max_length=1)),
                ('ambience', models.CharField(max_length=1)),
                ('active_aging', models.CharField(max_length=1)),
                ('motivation', models.TextField()),
                ('people_class', models.IntegerField()),
                ('loe_income', models.CharField(max_length=1)),
                ('partnership', models.TextField()),
                ('home_care', models.CharField(max_length=1)),
                ('requisites', models.TextField()),
                ('activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities_section.Activity')),
                ('contact', models.ManyToManyField(to='institution_section.Contact')),
                ('instructor', models.ManyToManyField(to='institution_section.Instructor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Location')),
                ('responsible', models.ManyToManyField(to='institution_section.Responsible')),
            ],
        ),
    ]
