# Generated by Django 3.0.7 on 2020-08-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_section', '0002_auto_20200818_1212'),
        ('institution_section', '0004_auto_20200818_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
