# Generated by Django 3.0.7 on 2020-08-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0006_auto_20200818_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='assitence',
            field=models.ManyToManyField(null=True, through='institution_section.ActingTime', to='institution_section.AssistanceModality'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contactMeans',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.ContactMeans'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='webAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.WebAddress'),
        ),
    ]
