# Generated by Django 3.0.7 on 2020-08-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0007_auto_20200818_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='name',
            new_name='cityName',
        ),
    ]
