# Generated by Django 2.2.6 on 2020-10-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0008_auto_20200821_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeDigitalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypePhoneEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebAddressInstitution',
            fields=[
                ('webaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.WebAddress')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.webaddress',),
        ),
        migrations.CreateModel(
            name='WebAddressLocals',
            fields=[
                ('webaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.WebAddress')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.webaddress',),
        ),
        migrations.CreateModel(
            name='WebAddressProfessional',
            fields=[
                ('webaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.WebAddress')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.webaddress',),
        ),
        migrations.RenameField(
            model_name='webaddress',
            old_name='facebook',
            new_name='digitalAddress',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='contactMeans',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='webAddress',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='contactMeans',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='webAddress',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='contactMeans',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='webAddress',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='tweeter',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='webPage',
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(default='nda', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(default='nda', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='assitence',
            field=models.ManyToManyField(through='institution_section.ActingTime', to='institution_section.AssistanceModality'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='activities',
            field=models.ManyToManyField(related_name='atividades_ofertadas', to='activities_section.Activity'),
        ),
        migrations.CreateModel(
            name='EmailInstitution',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Email')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.email',),
        ),
        migrations.CreateModel(
            name='EmailLocals',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Email')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.email',),
        ),
        migrations.CreateModel(
            name='EmailProfessional',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Email')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.email',),
        ),
        migrations.CreateModel(
            name='PhoneInstitution',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Phone')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.phone',),
        ),
        migrations.CreateModel(
            name='PhoneLocals',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Phone')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.phone',),
        ),
        migrations.CreateModel(
            name='PhoneProfessional',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution_section.Phone')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('institution_section.phone',),
        ),
        migrations.DeleteModel(
            name='ContactMeans',
        ),
        migrations.AddField(
            model_name='webaddressprofessional',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Professional'),
        ),
        migrations.AddField(
            model_name='webaddresslocals',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Locals'),
        ),
        migrations.AddField(
            model_name='webaddressinstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Institution'),
        ),
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='institution',
            name='webAddressList',
            field=models.ManyToManyField(related_name='paginas_instituicao', through='institution_section.WebAddressInstitution', to='institution_section.TypeDigitalAddress'),
        ),
        migrations.AddField(
            model_name='locals',
            name='webAddressList',
            field=models.ManyToManyField(related_name='paginas_local', through='institution_section.WebAddressLocals', to='institution_section.TypeDigitalAddress'),
        ),
        migrations.AddField(
            model_name='professional',
            name='webAddressList',
            field=models.ManyToManyField(related_name='paginas_professional', through='institution_section.WebAddressProfessional', to='institution_section.TypeDigitalAddress'),
        ),
        migrations.AddField(
            model_name='webaddress',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='institution_section.TypeDigitalAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneprofessional',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Professional'),
        ),
        migrations.AddField(
            model_name='phonelocals',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Locals'),
        ),
        migrations.AddField(
            model_name='phoneinstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Institution'),
        ),
        migrations.AddField(
            model_name='emailprofessional',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Professional'),
        ),
        migrations.AddField(
            model_name='emaillocals',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Locals'),
        ),
        migrations.AddField(
            model_name='emailinstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_section.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='emailList',
            field=models.ManyToManyField(related_name='emails_institution', through='institution_section.EmailInstitution', to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phoneList',
            field=models.ManyToManyField(related_name='telefones_instituicao', through='institution_section.PhoneInstitution', to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='locals',
            name='emailList',
            field=models.ManyToManyField(related_name='emails_local', through='institution_section.EmailLocals', to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='locals',
            name='phoneList',
            field=models.ManyToManyField(related_name='telefones_local', through='institution_section.PhoneLocals', to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='professional',
            name='emailList',
            field=models.ManyToManyField(related_name='emails_professional', through='institution_section.EmailProfessional', to='institution_section.TypePhoneEmail'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phoneList',
            field=models.ManyToManyField(related_name='telefones_professional', through='institution_section.PhoneProfessional', to='institution_section.TypePhoneEmail'),
        ),
    ]
