# Generated by Django 2.2.6 on 2020-11-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0010_auto_20201110_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_place', models.CharField(blank=True, max_length=75)),
                ('number_place', models.CharField(blank=True, max_length=8)),
                ('complement', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('reference_point', models.CharField(blank=True, max_length=50)),
                ('haveParking', models.BooleanField(blank=True, null=True)),
                ('parkingDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='AssistanceModality',
            new_name='ActingArea',
        ),
        migrations.RemoveField(
            model_name='address',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='emaillocals',
            name='email_ptr',
        ),
        migrations.RemoveField(
            model_name='emaillocals',
            name='local',
        ),
        migrations.RemoveField(
            model_name='emailprofessional',
            name='email_ptr',
        ),
        migrations.RemoveField(
            model_name='emailprofessional',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='address',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='emailList',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='phoneList',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='targetAudience',
        ),
        migrations.RemoveField(
            model_name='locals',
            name='webAddressList',
        ),
        migrations.RemoveField(
            model_name='longaduracao',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='phonelocals',
            name='local',
        ),
        migrations.RemoveField(
            model_name='phonelocals',
            name='phone_ptr',
        ),
        migrations.RemoveField(
            model_name='phoneprofessional',
            name='phone_ptr',
        ),
        migrations.RemoveField(
            model_name='phoneprofessional',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='webaddresslocals',
            name='local',
        ),
        migrations.RemoveField(
            model_name='webaddresslocals',
            name='webaddress_ptr',
        ),
        migrations.RemoveField(
            model_name='webaddressprofessional',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='webaddressprofessional',
            name='webaddress_ptr',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='CAD',
            new_name='capacity_free_f',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='CAD_F',
            new_name='capacity_free_m',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='CAD_M',
            new_name='capacity_used_f',
        ),
        migrations.RenameField(
            model_name='capacity',
            old_name='CAP',
            new_name='capacity_used_m',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='companyFancyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='foundedIn',
            new_name='foundation_year',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='companyName',
            new_name='legal_nature',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='legalKind',
            new_name='trading_name',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='CAP_F',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='CAP_M',
        ),
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='CNPJ',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='assitenceModality',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='emailList',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='phoneList',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='webAddressList',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='healthyAging',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='home_care',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='emailList',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='phoneList',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='webAddressList',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='type',
        ),
        migrations.AddField(
            model_name='academiceducation',
            name='description',
            field=models.CharField(default='1', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='expertiseareas',
            name='description',
            field=models.CharField(default='1', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='capacity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.Capacity'),
        ),
        migrations.AddField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='mainActingArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.ActingArea'),
        ),
        migrations.AddField(
            model_name='institution',
            name='technicalResponsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.Professional'),
        ),
        migrations.AddField(
            model_name='institution',
            name='trading_name_know',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.Institution'),
        ),
        migrations.AddField(
            model_name='offers',
            name='peopleRecommender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_incapacity',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_range_age',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_sex',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='people_can_be_served',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='webaddress',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cityName',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='country',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='state',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='academicEducation',
            field=models.ManyToManyField(null=True, to='institution_section.AcademicEducation'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='expertiseAreas',
            field=models.ManyToManyField(null=True, to='institution_section.ExpertiseAreas'),
        ),
        migrations.DeleteModel(
            name='ActingTime',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='EmailLocals',
        ),
        migrations.DeleteModel(
            name='EmailProfessional',
        ),
        migrations.DeleteModel(
            name='Locals',
        ),
        migrations.DeleteModel(
            name='LongaDuracao',
        ),
        migrations.DeleteModel(
            name='PhoneLocals',
        ),
        migrations.DeleteModel(
            name='PhoneProfessional',
        ),
        migrations.DeleteModel(
            name='WebAddressLocals',
        ),
        migrations.DeleteModel(
            name='WebAddressProfessional',
        ),
        migrations.AddField(
            model_name='addressplace',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.Cidade'),
        ),
        migrations.AddField(
            model_name='institution',
            name='addressPlace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_section.AddressPlace'),
        ),
    ]
