# Generated by Django 3.1.6 on 2021-08-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0013_auto_20210806_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_incapacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.peopleincapacity'),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_range_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.peoplerangeage'),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.peoplesex'),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='most_people_served_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_served', to='institution_section.peopletype'),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='people_can_be_served',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_most_served', to='institution_section.peopletype'),
        ),
    ]
