# Generated by Django 3.1.6 on 2021-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0014_auto_20210806_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='webPage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
