# Generated by Django 3.1.6 on 2021-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0015_institution_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actingarea',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actingarea',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
