# Generated by Django 3.1.6 on 2021-08-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0016_auto_20210809_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webaddress',
            name='description',
        ),
        migrations.AlterField(
            model_name='typedigitaladdress',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
