# Generated by Django 3.1.6 on 2021-08-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0017_auto_20210810_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaddress',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution_section.typedigitaladdress'),
        ),
    ]
