# Generated by Django 3.1.6 on 2021-08-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0018_webaddress_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedigitaladdress',
            name='type',
        ),
    ]
