# Generated by Django 3.1.6 on 2021-08-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0019_remove_typedigitaladdress_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actingarea',
            name='description',
        ),
    ]
