# Generated by Django 2.2.4 on 2019-09-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActionsPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(to='assessment_section.Actions', verbose_name='Ações')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DemandsProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do Problema ou Demanda')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[['C', 'Curto'], ['M', 'Médio'], ['L', 'Longo']], default='C', max_length=1, verbose_name='Prazo de implementação')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReassessmentControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('action_result', models.CharField(max_length=100, null=True, verbose_name='Ação/resultado')),
                ('adequacy', models.CharField(max_length=100, null=True, verbose_name='Adequação/Metas/Ações')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DemandMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('dm3_unmet_demands', models.TextField(null=True, verbose_name='O(a) idoso(a) apresenta outras demandas não contempladas no mapa? Se sim, especificar:')),
                ('gerontologist_assessment', models.TextField(null=True, verbose_name='Avaliação do Gerontólogo')),
                ('actions_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_section.ActionsPlanning', verbose_name='Planejamento das Ações')),
            ],
            options={
                'verbose_name': 'Mapa das Demandas',
                'verbose_name_plural': 'Mapa das Demandas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='actionsplanning',
            name='demand_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_section.DemandsProblems', verbose_name='Demanda/Problema'),
        ),
        migrations.AddField(
            model_name='actionsplanning',
            name='goals',
            field=models.ManyToManyField(to='assessment_section.Goals', verbose_name='Establecimento de Metas'),
        ),
        migrations.AddField(
            model_name='actionsplanning',
            name='services',
            field=models.ManyToManyField(to='assessment_section.Services', verbose_name='Serviços'),
        ),
        migrations.CreateModel(
            name='ActionImplementationCoordenation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_section.Actions', verbose_name='Ação Implementada')),
                ('expertise', models.ManyToManyField(to='experts_section.Expertise', verbose_name='Profissionais Envolvidos')),
                ('services', models.ManyToManyField(to='assessment_section.Services', verbose_name='Serviços realizados')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
