# Generated by Django 2.2.4 on 2019-09-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActionsImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_section.Actions')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentsControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('results', models.TextField()),
                ('adequacy', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DemandsProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('actions', models.ManyToManyField(through='assessment_section.ActionsImplementation', to='assessment_section.Actions')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='actionsimplementation',
            name='assessmentsControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actionImplementation', to='assessment_section.AssessmentsControl'),
        ),
        migrations.AddField(
            model_name='actionsimplementation',
            name='expert',
            field=models.ManyToManyField(related_name='actionImplementation', to='experts_section.Expert'),
        ),
        migrations.AddField(
            model_name='actionsimplementation',
            name='expertAssessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_section.ExpertAssessment'),
        ),
        migrations.AddField(
            model_name='actionsimplementation',
            name='expertise',
            field=models.ManyToManyField(related_name='actionImplementation', to='experts_section.Expertise'),
        ),
        migrations.AddField(
            model_name='actionsimplementation',
            name='services',
            field=models.ManyToManyField(related_name='actionImplementation', to='assessment_section.Services'),
        ),
    ]
