# Generated by Django 2.2.4 on 2019-10-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandmap',
            name='actions_planning',
        ),
        migrations.AddField(
            model_name='demandmap',
            name='actions_organization',
            field=models.TextField(null=True, verbose_name='Organização das Ações'),
        ),
        migrations.AddField(
            model_name='demandmap',
            name='control',
            field=models.TextField(null=True, verbose_name='Controle / Reavaliação'),
        ),
        migrations.AddField(
            model_name='demandmap',
            name='coordenation_implementation',
            field=models.TextField(null=True, verbose_name='Coordenação / Implementação'),
        ),
        migrations.AddField(
            model_name='demandmap',
            name='demands_problems',
            field=models.TextField(null=True, verbose_name='Demandas/Problemas'),
        ),
        migrations.AddField(
            model_name='demandmap',
            name='goals',
            field=models.TextField(null=True, verbose_name='Metas'),
        ),
    ]
