# Generated by Django 2.2.6 on 2020-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_section', '0002_auto_20200911_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandmap',
            name='actions_organization',
            field=models.TextField(blank=True, null=True, verbose_name='Organização das Ações'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='control',
            field=models.TextField(blank=True, null=True, verbose_name='Controle / Reavaliação'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='coordenation_implementation',
            field=models.TextField(blank=True, null=True, verbose_name='Coordenação / Implementação'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='demands_problems',
            field=models.TextField(blank=True, null=True, verbose_name='Demandas/Problemas'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='dm3_unmet_demands',
            field=models.TextField(blank=True, null=True, verbose_name='O(a) idoso(a) apresenta outras demandas não contempladas no mapa? Se sim, especificar:'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='gerontologist_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação do Gerontólogo'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Metas'),
        ),
    ]
