from django.contrib import admin
from page_section.models import *

admin.site.register(Page)
admin.site.register(CognitionDeficit)
admin.site.register(AgingAspects)
admin.site.register(NegativeAttitudesAging)
admin.site.register(Depression)
admin.site.register(PsychologicalAspects)
admin.site.register(SensoryDeficit)
admin.site.register(FunctionalDisability)
admin.site.register(Malnutrition)
admin.site.register(CardiovascularFactors)
admin.site.register(MisuseMedications)
admin.site.register(BiologicalAspects)
admin.site.register(LowSocialSupport)
admin.site.register(EnvironmentalProblems)
admin.site.register(Violence)
admin.site.register(SocialAspects)
admin.site.register(Falls)
admin.site.register(MultidisciplinaryDomain)
admin.site.register(DemandMap)
admin.site.register(RecommendedActivities)
