# Generated by Django 2.2.4 on 2019-09-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('communication', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalsActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooling', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_time', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_situations', to='institution_section.Address')),
                ('current_situation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_situation', to='participant_section.Participant')),
                ('history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='situation_history', to='participant_section.Participant')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_situations', to='participant_section.Income')),
                ('lives_with', models.ManyToManyField(related_name='lives_with', to='participant_section.ParticipantSocialMedia')),
                ('marital_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_situations', to='participant_section.MaritalStatus')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_situations', to='participant_section.Religion')),
                ('retire_professionals_activities', models.ManyToManyField(blank=True, related_name='retire_participant_situations', to='participant_section.ProfessionalsActivities')),
                ('rides_with', models.ManyToManyField(related_name='rides_with', to='participant_section.ParticipantSocialMedia')),
                ('schooling', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_situations', to='participant_section.Schooling')),
                ('work_professionals_activities', models.ManyToManyField(blank=True, related_name='work_participant_situations', to='participant_section.ProfessionalsActivities')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
