# Generated by Django 2.2.7 on 2020-02-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p00_email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email da Google')),
                ('p01_name', models.CharField(max_length=50, verbose_name='Nome:')),
                ('p02_address', models.CharField(max_length=80, verbose_name='Endereço')),
                ('p03_communication', models.CharField(max_length=100, verbose_name='Meios de Entrar em contato')),
                ('p04_birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('p05_age', models.IntegerField(verbose_name='Idade Atual')),
                ('p06_gender', models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1, verbose_name='Gênero:')),
                ('p20_profile_photo_URL', models.ImageField(null=True, upload_to='profile_photos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p07_marital_status', models.CharField(choices=[['Solteiro(a)', 'Solteiro(a)'], ['Casado(a)/União Estável', 'Casado(a)/União Estável'], ['Separado(a)/Divorciado(a)', 'Separado(a)/Divorciado(a)'], ['Viúvo(a)', 'Viúvo(a)']], max_length=30, verbose_name='Estado Civil')),
                ('p08_schooling', models.CharField(choices=[['analfabeto', 'analfabeto'], ['ensino fundamental (incompleto)', 'ensino fundamental (incompleto)'], ['ensino fundamental (completo)', 'ensino fundamental (completo)'], ['ensino médio (incompleto)', 'ensino médio (incompleto)'], ['ensino médio (completo)', 'ensino médio (completo)'], ['ensino superior (incompleto)', 'ensino superior (incompleto)'], ['ensino superior (completo)', 'ensino superior (completo)'], ['ensino supeiror (com pós-graduação)', 'ensino supeiror (com pós-graduação)']], max_length=35, verbose_name='Escolaridade')),
                ('p09_study_time', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Estudo')),
                ('p10_is_retired', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='É Aposentado ou pensionista?')),
                ('p10_retired_profession', models.CharField(blank=True, max_length=30, null=True, verbose_name='Aposentado por qual profissao')),
                ('p10_actual_profession', models.CharField(blank=True, max_length=30, null=True, verbose_name='Profissão Atual')),
                ('p11_retire_more_time_activity', models.CharField(blank='True', max_length=30, null=True, verbose_name='Se aposentado, qual profissão exerceu por mais tempo')),
                ('p12_is_working_professionals_activities', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='Exerce atividade remunerada?')),
                ('p12_professional_activities', models.CharField(blank=True, max_length=30, null=True, verbose_name='Atividade Remunerada exercida:')),
                ('p13_income_I', models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['Entre 1 e 2 salários mínimos', 'Entre 1 e 2 salários mínimos'], ['Entre 2 e 3 salários mínimos', 'Entre 2 e 3 salários mínimos'], ['Entre 3 e 4 salários mínimos', 'Entre 3 e 4 salários mínimos'], ['Entre 4 e 5 salários mínimos', 'Entre 4 e 5 salários mínimos'], ['Entre 5 e 10 salários mínimos', 'Entre 5 e 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Individual:')),
                ('p13_income_F', models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['Entre 1 e 2 salários mínimos', 'Entre 1 e 2 salários mínimos'], ['Entre 2 e 3 salários mínimos', 'Entre 2 e 3 salários mínimos'], ['Entre 3 e 4 salários mínimos', 'Entre 3 e 4 salários mínimos'], ['Entre 4 e 5 salários mínimos', 'Entre 4 e 5 salários mínimos'], ['Entre 5 e 10 salários mínimos', 'Entre 5 e 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Familiar:')),
                ('p14_lives_with', models.TextField(blank=True, null=True, verbose_name='Com quem mora')),
                ('p15_has_religion', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='Possui Religião')),
                ('p15_religion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Religião')),
                ('p16_health_self_report', models.TextField(blank=True, null=True, verbose_name='Auto Relato de Saúde')),
                ('p20_weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('p20_height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('p20_IMC', models.FloatField(blank=True, null=True, verbose_name='IMC')),
                ('p30_car', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Possui Carro?')),
                ('p30_bus', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Utiliza tranporte público?')),
                ('p30_uber', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Utiliza transporte por aplicativo ou taxi?')),
                ('p30_ride', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Costuma pegar carona?')),
                ('p30_ride_with', models.TextField(blank=True, null=True, verbose_name='Pessoas com a qual pega carona')),
                ('p31_comments', models.TextField(blank=True, null=True, verbose_name='Comentários sobre o Participante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalsActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooling', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
