# Generated by Django 2.2.4 on 2019-08-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsituation',
            name='page',
        ),
    ]
