# Generated by Django 2.2.4 on 2019-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photograph',
            field=models.ImageField(blank='True', null=True, upload_to='Fotos_participantes'),
        ),
    ]
