# Generated by Django 2.2.6 on 2020-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsituation',
            name='p10_retired_profession',
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p02_address',
            field=models.CharField(default='teste', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p03_communication',
            field=models.CharField(default='teste', max_length=100, verbose_name='Meios de Entrar em contato'),
            preserve_default=False,
        ),
    ]
