# Generated by Django 2.2.6 on 2019-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantsituation',
            old_name='p15_have_religion',
            new_name='p15_has_religion',
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_F',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['mais de 1 a 2 salários mínimos', 'mais de 1 a 2 salários mínimos'], ['mais de 2 a 3 salários mínimos', 'mais de 2 a 3 salários mínimos'], ['mais de 3 a 4 salários mínimos', 'mais de 3 a 4 salários mínimos'], ['mais de 4 a 5 salários mínimos', 'mais de 4 a 5 salários mínimos'], ['mais de 5 a 10 salários mínimos', 'mais de 5 a 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Familiar:'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_I',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['mais de 1 a 2 salários mínimos', 'mais de 1 a 2 salários mínimos'], ['mais de 2 a 3 salários mínimos', 'mais de 2 a 3 salários mínimos'], ['mais de 3 a 4 salários mínimos', 'mais de 3 a 4 salários mínimos'], ['mais de 4 a 5 salários mínimos', 'mais de 4 a 5 salários mínimos'], ['mais de 5 a 10 salários mínimos', 'mais de 5 a 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Individual:'),
        ),
    ]
