# Generated by Django 2.2.4 on 2019-10-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsituation',
            name='p07_marital_status',
            field=models.CharField(choices=[['Solteiro(a)', 'Solteiro(a)'], ['Casado(a)/União Estável', 'Casado(a)/União Estável'], ['Separado(a)/Divorciado(a)', 'Separado(a)/Divorciado(a)'], ['Viúvo(a)', 'Viúvo(a)']], max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p08_schooling',
            field=models.CharField(choices=[['analfabeto', 'analfabeto'], ['ensino fundamental (incompleto)', 'ensino fundamental (incompleto)'], ['ensino fundamental (completo)', 'ensino fundamental (completo)'], ['ensino médio (incompleto)', 'ensino médio (incompleto)'], ['ensino médio (completo)', 'ensino médio (completo)'], ['ensino superior (incompleto)', 'ensino superior (incompleto)'], ['ensino superior (completo)', 'ensino superior (completo)'], ['ensino supeiror (com pós-graduação)', 'ensino supeiror (com pós-graduação)']], max_length=35, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p09_study_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de Estudo'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p10_actual_profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Profissão Atual'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p10_is_retired',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='É Aposentado ou pensionista?'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p10_retired_profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aposentado por qual profissao'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p12_is_working_professionals_activities',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='Exerce atividade remunerada?'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p12_professional_activite',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atividade Remunerada exercida:'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_F',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['mais de 1 a 2 salários mínimos', 'mais de 1 a 2 salários mínimos'], ['mais de 2 a 3 salários mínimos', 'mais de 2 a 3 salários mínimos'], ['mais de 3 a 4 salários mínimos', 'mais de 3 a 4 salários mínimos'], ['mais de 4 a 5 salários mínimos', 'mais de 4 a 5 salários mínimos'], ['mais de 5 a 10 salários mínimos', 'mais de 5 a 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=30, verbose_name='Rendimento Mensal Familiar:'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_I',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['mais de 1 a 2 salários mínimos', 'mais de 1 a 2 salários mínimos'], ['mais de 2 a 3 salários mínimos', 'mais de 2 a 3 salários mínimos'], ['mais de 3 a 4 salários mínimos', 'mais de 3 a 4 salários mínimos'], ['mais de 4 a 5 salários mínimos', 'mais de 4 a 5 salários mínimos'], ['mais de 5 a 10 salários mínimos', 'mais de 5 a 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=30, verbose_name='Rendimento Mensal Individual:'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p15_have_religion',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, verbose_name='Possui Religião'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p15_religion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p20_IMC',
            field=models.FloatField(blank=True, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p20_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p20_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso'),
        ),
    ]
