# Generated by Django 2.2.4 on 2019-09-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0002_participant_photograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='photograph',
        ),
    ]
