# Generated by Django 2.2.6 on 2020-05-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0002_auto_20200511_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsituation',
            name='p16_health_self_report',
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p16_health_monitoring',
            field=models.TextField(null=True, verbose_name='Acompanhamento de saúde'),
        ),
    ]
