# Generated by Django 2.2.6 on 2019-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0002_auto_20191027_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsituation',
            name='p30_bus',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Utiliza tranporte público?'),
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p30_car',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Possui Carro?'),
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p30_ride',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Costuma pegar carona?'),
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p30_uber',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Utiliza transporte por aplicativo ou taxi?'),
        ),
        migrations.AddField(
            model_name='participantsituation',
            name='p31_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários sobre o Participante'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='p06_gender',
            field=models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1, verbose_name='Gênero:'),
        ),
    ]
