# Generated by Django 2.2.6 on 2020-09-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0003_auto_20200528_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantsituation',
            old_name='p16_health_monitoring',
            new_name='p16_health_self_report',
        ),
    ]
