# Generated by Django 2.2.7 on 2019-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0003_auto_20191120_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_F',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['Entre 1 e 2 salários mínimos', 'Entre 1 e 2 salários mínimos'], ['Entre 2 e 3 salários mínimos', 'Entre 2 e 3 salários mínimos'], ['Entre 3 e 4 salários mínimos', 'Entre 3 e 4 salários mínimos'], ['Entre 4 e 5 salários mínimos', 'Entre 4 e 5 salários mínimos'], ['Entre 5 e 10 salários mínimos', 'Entre 5 e 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Familiar:'),
        ),
        migrations.AlterField(
            model_name='participantsituation',
            name='p13_income_I',
            field=models.CharField(choices=[['BPC', 'BPC'], ['Até um salário mínimo', 'Até um salário mínimo'], ['Entre 1 e 2 salários mínimos', 'Entre 1 e 2 salários mínimos'], ['Entre 2 e 3 salários mínimos', 'Entre 2 e 3 salários mínimos'], ['Entre 3 e 4 salários mínimos', 'Entre 3 e 4 salários mínimos'], ['Entre 4 e 5 salários mínimos', 'Entre 4 e 5 salários mínimos'], ['Entre 5 e 10 salários mínimos', 'Entre 5 e 10 salários mínimos'], ['mais de 10 salários mínimos', 'mais de 10 salários mínimos']], max_length=70, verbose_name='Rendimento Mensal Individual:'),
        ),
    ]
