# Generated by Django 2.2.6 on 2020-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_section', '0005_auto_20200925_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='p01_name_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome:'),
        ),
    ]
