# Generated by Django 2.2.4 on 2019-09-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgingAspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalAspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CardiovascularFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q33DCVFamiliarHistory', models.BooleanField()),
                ('q34Hypertension', models.BooleanField()),
                ('q35UncontrolledDiabetes', models.BooleanField()),
                ('q35UnknownValueGlycemia', models.BooleanField()),
                ('q36Cholesterol', models.BooleanField()),
                ('q36UnknownValueCT_HDL', models.BooleanField()),
                ('q37Smoker', models.BooleanField()),
                ('q38Practice150MinutesExercises', models.BooleanField()),
                ('q39HealthyEating', models.BooleanField()),
                ('q41BMI_Obesity', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CognitionDeficit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1MemoryGoodLikeBefore', models.BooleanField()),
                ('q2MemoryTest', models.BooleanField()),
                ('q3LanguageFunctionAttention', models.BooleanField()),
                ('q4VisospatialAbility', models.BooleanField()),
                ('q4VisospatialAbilityScore', models.IntegerField()),
                ('q5Praxia', models.BooleanField()),
                ('q6MemoryTest', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('q9SatisfiedWithLife', models.BooleanField()),
                ('q10FrequentlySad', models.BooleanField()),
                ('q11StoppedDoingThings', models.BooleanField()),
                ('q12FearBadThingsHappen', models.BooleanField()),
                ('q13ImpatientDisquiet', models.BooleanField()),
                ('q14ConcentrationProblem', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q73ManicureSidewalks', models.BooleanField()),
                ('q74PublicTransportAccess', models.BooleanField()),
                ('q75CommerceAccess', models.BooleanField()),
                ('q76EasePlasewalking', models.BooleanField()),
                ('q77FunAccess', models.BooleanField()),
                ('q78Safety', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Falls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q87FallsLastYear', models.BooleanField()),
                ('q88AmountFallsLastYear', models.IntegerField()),
                ('q89FracturesDueToFalls', models.BooleanField()),
                ('q90Strength_MMII', models.BooleanField()),
                ('q91Equilibrium', models.BooleanField()),
                ('q92OlderThan75', models.BooleanField()),
                ('q93Female', models.BooleanField()),
                ('q94CognitiveAlterations', models.BooleanField()),
                ('q95AVDsCommitment', models.BooleanField()),
                ('q96VisualDeficit', models.BooleanField()),
                ('q97DomesticRisks', models.BooleanField()),
                ('q98BehaviorRisk', models.BooleanField()),
                ('q99Inactivity', models.BooleanField()),
                ('q100PriorAVE', models.BooleanField()),
                ('q101PsychotropicMedicationsUse', models.BooleanField()),
                ('q102HasDiseases', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalDisability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q20ToShop', models.BooleanField()),
                ('q21UseTransport', models.BooleanField()),
                ('q22ToCook', models.BooleanField()),
                ('q23UseTelephone', models.BooleanField()),
                ('q24DressUp', models.BooleanField()),
                ('q25TakeShower', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InternalEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q63EstableFurniture', models.BooleanField()),
                ('q64LooseObjectsCarpets', models.BooleanField()),
                ('q65SlipperyFloor', models.BooleanField()),
                ('Q66HandrailOnStairs', models.BooleanField()),
                ('q67LightedStairs', models.BooleanField()),
                ('q68SuitableStairsSteps', models.BooleanField()),
                ('q69NonSlipperyCarpet', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LowSocialSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q54Spouse', models.BooleanField()),
                ('q54Mother', models.BooleanField()),
                ('q53Father', models.BooleanField()),
                ('q54Brothers', models.IntegerField()),
                ('q54Children', models.IntegerField()),
                ('q54GranChildren', models.IntegerField()),
                ('q55MeetFamilyFriends', models.BooleanField()),
                ('q56ParticipateFamilyDecisions', models.BooleanField()),
                ('q57SatisfiedFamilyRelationship', models.BooleanField()),
                ('q58HelpedIfNeedMoney', models.BooleanField()),
                ('q59SomeoneHelpsIfNeed', models.BooleanField()),
                ('q60SomeoneToHaveFun', models.BooleanField()),
                ('q61ParticipateSocialEvents', models.BooleanField()),
                ('q62RegularyHealtServices', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Malnutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d26YourselfMalnourished', models.BooleanField()),
                ('d27ChewingMouthProblems', models.BooleanField()),
                ('d28Less3MealDaily', models.BooleanField()),
                ('d29DecreasesAmountFood', models.BooleanField()),
                ('d30LostWeightNoReason', models.BooleanField()),
                ('d30LostWeightNoReasonAmount', models.IntegerField()),
                ('d31StressIllnessHospitalization', models.BooleanField()),
                ('q32BMI_Less22', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MisuseMedications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q44AmountDiagnostics', models.IntegerField()),
                ('q46MedicinesIncrease', models.BooleanField()),
                ('q47KnowMedicines', models.BooleanField()),
                ('q48MedicationsPrecribed', models.BooleanField()),
                ('q49MedicineMedicalAdvice', models.BooleanField()),
                ('q50AlreadyStoppedMedicines', models.BooleanField()),
                ('q51SelfMedication', models.BooleanField()),
                ('q52InappropriateMedication', models.BooleanField()),
                ('q53RiskAdverseReaction', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultidisciplinaryDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NegativeAttitudesAging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q7AgeSelfPerception', models.IntegerField()),
                ('q7AgeSelfPerceptionWhy', models.TextField()),
                ('q7AgeSelfPerceptionAnalyze', models.BooleanField()),
                ('q8AgingAnalyse', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('selfHealthReport', models.TextField(null=True)),
                ('unmetDemands', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PsychologicalAspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('systemRating', models.IntegerField()),
                ('expertRating', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('expertConsideration', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RiskBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q70GetOnStool', models.BooleanField()),
                ('q71TurnLightsOff', models.BooleanField()),
                ('q72SafeShoes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SensoryDeficit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q15VisionProblems', models.BooleanField()),
                ('q16HearingProblems', models.BooleanField()),
                ('q17TasteProblems', models.BooleanField()),
                ('q18SensesProblems', models.BooleanField()),
                ('q19InteractionProblems', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q79AfraidClosePerson', models.BooleanField()),
                ('q80FeelsAbandoned', models.BooleanField()),
                ('q81Forced', models.BooleanField()),
                ('q82Assauteld', models.BooleanField()),
                ('q83InNeed', models.BooleanField()),
                ('q84SomeoneUsedMoney', models.BooleanField()),
                ('q85TouchedWithoutPermission', models.BooleanField()),
                ('q86DontTakeCareHealth', models.BooleanField()),
                ('maxScore', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialAspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('maxScore', models.IntegerField()),
                ('environmentalProblems', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.EnvironmentalProblems')),
                ('lowSocialSupport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.LowSocialSupport')),
                ('violence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.Violence')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
