# Generated by Django 2.2.4 on 2019-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malnutrition',
            name='d30_lost_weight_no_reason',
            field=models.CharField(choices=[['Não', 'Não'], ['Não sabe', 'Não sabe'], ['Mais de 3 KG', 'Mais de 3 Kg'], ['Entre 1 e 3 KG', 'Entre 1 e 3 KG']], default='N', max_length=15, verbose_name='30. Nos últimos 3 meses, o(a) senhor(a) Perdeu peso sem motivo aparente?'),
        ),
    ]
