# Generated by Django 2.2.6 on 2019-11-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='gerontologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts_section.Expert', verbose_name='Gerontologista Resposável'),
        ),
    ]
