# Generated by Django 2.2.4 on 2019-09-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_section', '0001_initial'),
        ('drinks_section', '0001_initial'),
        ('review_section', '0001_initial'),
        ('assessment_section', '0001_initial'),
        ('health_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedactivities',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_section.Offers'),
        ),
        migrations.AddField(
            model_name='recommendedactivities',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_section.Page'),
        ),
        migrations.AddField(
            model_name='psychologicalaspects',
            name='cognitionDeficit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.CognitionDeficit'),
        ),
        migrations.AddField(
            model_name='psychologicalaspects',
            name='depression',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.Depression'),
        ),
        migrations.AddField(
            model_name='psychologicalaspects',
            name='negativeAttitudesAging',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.NegativeAttitudesAging'),
        ),
        migrations.AddField(
            model_name='page',
            name='biologicalAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.BiologicalAspects'),
        ),
        migrations.AddField(
            model_name='page',
            name='expertAssessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment_section.ExpertAssessment'),
        ),
        migrations.AddField(
            model_name='page',
            name='multidisciplinaryDomain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.MultidisciplinaryDomain'),
        ),
        migrations.AddField(
            model_name='page',
            name='psychologicalAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.PsychologicalAspects'),
        ),
        migrations.AddField(
            model_name='page',
            name='recommendedActivities',
            field=models.ManyToManyField(null=True, related_name='page', through='page_section.RecommendedActivities', to='review_section.Offers'),
        ),
        migrations.AddField(
            model_name='page',
            name='socialAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.SocialAspects'),
        ),
        migrations.AddField(
            model_name='negativeattitudesaging',
            name='q8AgingNegativePoints',
            field=models.ManyToManyField(null=True, related_name='NegativePoints', to='page_section.AgingAspects'),
        ),
        migrations.AddField(
            model_name='negativeattitudesaging',
            name='q8AgingPositivePoints',
            field=models.ManyToManyField(null=True, related_name='PositivePoints', to='page_section.AgingAspects'),
        ),
        migrations.AddField(
            model_name='multidisciplinarydomain',
            name='falls',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.Falls'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42DiseasesLast5Years',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.Diseases'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43HealthProblems',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.HealthProblems'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q45Medicines',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.Medicines'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q89FracturesList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_section.Fractures'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='externalEnvironment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.ExternalEnvironment'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='internalEnvironment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.InternalEnvironment'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='riskBehavior',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.RiskBehavior'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q40AlcoholIngestedLastWeek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drinks_section.IngestedDrinks'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='cardiovascularFactors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.CardiovascularFactors'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='functionalDisability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.FunctionalDisability'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='malNutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.Malnutrition'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='misuseMedications',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.MisuseMedications'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='sensoryDeficit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.SensoryDeficit'),
        ),
    ]
