# Generated by Django 2.2.4 on 2019-09-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender_section', '0001_initial'),
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='recommendedActivities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender_section.RecommendedActivities', verbose_name='Atividades Recomendadas'),
        ),
        migrations.AddField(
            model_name='page',
            name='recommendedActivitiesOffers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender_section.RecommendedActivitiesOffers', verbose_name='Atividades Ofertadas Recomendadas'),
        ),
        migrations.AddField(
            model_name='page',
            name='socialAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.SocialAspects', verbose_name='Relacionados a Aspectos Sociais'),
        ),
        migrations.AddField(
            model_name='multidisciplinarydomain',
            name='falls',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.Falls'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='cardiovascularFactors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.CardiovascularFactors'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='functionalDisability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.FunctionalDisability'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='malNutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.Malnutrition'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='misuseMedications',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.MisuseMedications'),
        ),
        migrations.AddField(
            model_name='biologicalaspects',
            name='sensoryDeficit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_section.SensoryDeficit'),
        ),
    ]
