# Generated by Django 2.2.4 on 2019-09-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_section', '0002_gerontologist'),
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm3_unmet_demands', models.TextField(null=True)),
                ('gerontologist_assessment', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cognitiondeficit',
            old_name='q1MemoryGoodLikeBefore',
            new_name='q1_memory_good_like_before',
        ),
        migrations.RenameField(
            model_name='cognitiondeficit',
            old_name='q2MemoryTest',
            new_name='q2_memory_test',
        ),
        migrations.RenameField(
            model_name='depression',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='description',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q10FrequentlySad',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q11StoppedDoingThings',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q12FearBadThingsHappen',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q13ImpatientDisquiet',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q14ConcentrationProblem',
        ),
        migrations.RemoveField(
            model_name='depression',
            name='q9SatisfiedWithLife',
        ),
        migrations.RemoveField(
            model_name='page',
            name='selfHealthReport',
        ),
        migrations.RemoveField(
            model_name='page',
            name='unmetDemands',
        ),
        migrations.AddField(
            model_name='depression',
            name='q10_frequently_sad',
            field=models.BooleanField(default='False', verbose_name='O(A) senhor(a) se sente triste com frequência?'),
        ),
        migrations.AddField(
            model_name='depression',
            name='q11_stopped_doing_things',
            field=models.BooleanField(default='False', verbose_name='O(A) senhor(a) abandonou muitas coisas que fazia ou gostava de fazer?'),
        ),
        migrations.AddField(
            model_name='depression',
            name='q12_fear_bad_things_happen',
            field=models.BooleanField(default='False', verbose_name='O(A) senhor(a) tem medo que algum mal vá lhe acontecer?'),
        ),
        migrations.AddField(
            model_name='depression',
            name='q13_impatient_disquiet',
            field=models.BooleanField(default='False', verbose_name='O(A) senhor(a) se sente impaciente e agitado(a) com frequência?'),
        ),
        migrations.AddField(
            model_name='depression',
            name='q14_concentration_problem',
            field=models.BooleanField(default='False', verbose_name='O(A) senhor(a) tem dificuldade em se concentar?'),
        ),
        migrations.AddField(
            model_name='depression',
            name='q9_satisfied_with_life',
            field=models.BooleanField(default='False', verbose_name='De modo Geral Está Satisfeito com a vida?'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null='True', verbose_name='Criado em'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='page',
            name='gerontologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experts_section.Gerontologist'),
        ),
        migrations.AddField(
            model_name='page',
            name='p1_self_health_report',
            field=models.TextField(null=True, verbose_name='Auto Relato de Saúde - Como o senhor(a)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(null='True', verbose_name='Data da Entrevista'),
        ),
        migrations.AddField(
            model_name='page',
            name='demandMap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.DemandMap'),
        ),
    ]
