# Generated by Django 2.2.4 on 2019-08-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_section', '0001_initial'),
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DI_MedicationsManagement',
            new_name='DI_MedicationManagement',
        ),
    ]
