# Generated by Django 2.2.6 on 2020-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_15',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_30',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_45',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_60',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='entrance',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada no Serserviceviço'),
        ),
    ]
