# Generated by Django 2.2.4 on 2019-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0002_auto_20190814_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('systemRating', models.IntegerField()),
                ('expertRating', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('expertConsideration', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
    ]
