# Generated by Django 2.2.6 on 2020-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0002_auto_20200424_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d26_yourself_malnourished',
            new_name='q26_yourself_malnourished',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d27_chewing_mouth_problems',
            new_name='q27_chewing_mouth_problems',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d28_less3_meal_daily',
            new_name='q28_less3_meal_daily',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d29_decreases_amount_food',
            new_name='q29_decreases_amount_food',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d30_lost_weight_no_reason',
            new_name='q30_lost_weight_no_reason',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='d31_stress_illness_hospitalization',
            new_name='q31_stress_illness_hospitalization',
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='score_cognition',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='depression',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='q30_lost_weight_no_reason_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='q31_hospital',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='q31_illnes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='q31_stress',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='negativeattitudesaging',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
