# Generated by Django 2.2.6 on 2019-11-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0002_auto_20191103_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='interviewed',
            field=models.CharField(choices=[['Participante', 'Participante'], ['Cuidador Formal', 'Cuidador Formal'], ['Familiar', 'Familiar']], max_length=20, verbose_name='Pessoa entrevistada:'),
        ),
    ]
