# Generated by Django 2.2.4 on 2019-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0002_auto_20190920_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depression',
            name='q10_frequently_sad',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='10. O(A) senhor(a) se sente triste com frequência?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q11_stopped_doing_things',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='11. O(A) senhor(a) abandonou muitas coisas que fazia ou gostava de fazer?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q12_fear_bad_things_happen',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='12. O(A) senhor(a) tem medo que algum mal vá lhe acontecer?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q13_impatient_disquiet',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='13. O(A) senhor(a) se sente impaciente e agitado(a) com frequência?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q14_concentration_problem',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='14. O(A) senhor(a) tem dificuldade em se concentar?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q9_satisfied_with_life',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='9.De modo Geral Está Satisfeito com a vida?'),
        ),
    ]
