# Generated by Django 2.2.6 on 2019-11-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0003_auto_20191120_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q2_memory_test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_score',
            field=models.IntegerField(default=0, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q5_praxia_score',
            field=models.IntegerField(default=0, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='cognitiondeficit',
            name='q6_memory_test_score',
            field=models.IntegerField(default=0, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q2_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q5_praxia',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q6_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='6'),
        ),
    ]
