# Generated by Django 2.2.6 on 2020-09-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0003_auto_20200511_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='recommendedActivities',
        ),
        migrations.RemoveField(
            model_name='page',
            name='recommendedActivitiesOffers',
        ),
    ]
