# Generated by Django 2.2.4 on 2019-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0003_auto_20190920_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='depression',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
    ]
