# Generated by Django 2.2.4 on 2019-08-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0003_auto_20190817_1642'),
        ('review_section', '0002_auto_20190817_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedactivities',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_section.Offers'),
        ),
        migrations.AddField(
            model_name='recommendedactivities',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_section.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='recommendedActivities',
            field=models.ManyToManyField(related_name='page', through='page_section.RecommendedActivities', to='review_section.Offers'),
        ),
    ]
