# Generated by Django 2.2.6 on 2020-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0004_auto_20200903_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitiondeficit',
            name='score_cognition',
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='score',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='falls',
            name='score',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='score',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='violence',
            name='score',
            field=models.TextField(default=0, null=True),
        ),
    ]
