# Generated by Django 2.2.7 on 2019-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0004_auto_20191121_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='q34_hypertension_unknow',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='34. Desconhece os valores da PA?'),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='q35_unknown_value_glycemia',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='35. Desconhece os valores de glicemia?'),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='q36_unknown_value_ct_hdl',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='36. Desconhece os valores de CT e HDL?'),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='q40_alcohol_Ingested_last_week_amount',
            field=models.TextField(blank=True, null=True, verbose_name='40. Quantidade de Alcool Ingerido'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q2_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='2. Memória'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q2_memory_test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='2. Memória - Pontuação: (0 a 7)'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='3. Linguagem, função executiva e atenção'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention_score',
            field=models.IntegerField(default=0, verbose_name='3. Linguagem, função executiva e atenção - Pontuação: (0 a 100)'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q4_visospatial_ability_score',
            field=models.IntegerField(default=0, verbose_name='4. Habilidade visuoespacial - Pontuação: (0 a 4)'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q5_praxia',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='5. Praxia'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q5_praxia_score',
            field=models.IntegerField(default=0, verbose_name='5. Praxia - Pontuação: (0 a 3)'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q6_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='6. Memória'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q6_memory_test_score',
            field=models.IntegerField(default=0, verbose_name='6. Memória - Pontuação: (0 a 7)'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q66_handrail_on_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='66. Na casa do(a) senhor(a): As escadas possuem corrimão em ambos os lados? (Colocar sim se a casa não tive escadas)'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q67_lighted_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='67. Na casa do(a) senhor(a): As escadas/ degraus são iluminados adequadamente? (Colocar sim se a casa não tive escadas)'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q68_suitable_stairs_steps',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='68. Na casa do(a) senhor(a): Os degraus são adequados (tamanho, rebordos, largura e                    padronagem, etc)? (Colocar sim se a casa não tive escadas)'),
        ),
        migrations.AlterField(
            model_name='falls',
            name='q87_amount_falls_last_year',
            field=models.IntegerField(verbose_name='87. Se sofreu quedas, quantas?  [Se não, pontue também a resposta “não” na próxima questão e vá                       para a questão 90] [Se não, pule as próximas duas questões].'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_brothers',
            field=models.IntegerField(verbose_name='54. O(A) senhor(a) tem quantos irmãos?'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_children',
            field=models.IntegerField(verbose_name='54. O(A) senhor(a) tem quantos filhos?'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_father',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='54. O(A) senhor(a) tem: Pai?'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_gran_children',
            field=models.IntegerField(verbose_name='54. O(A) senhor(a) tem quantos netos?'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_mother',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='54. O(A) senhor(a) tem: Mãe?'),
        ),
        migrations.AlterField(
            model_name='lowsocialsupport',
            name='q54_spouse',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='54. O(A) senhor(a) tem: cônjuge?'),
        ),
        migrations.AlterField(
            model_name='malnutrition',
            name='d26_yourself_malnourished',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='26. O(A) senhor(a) acredita que está desnutrido?'),
        ),
        migrations.AlterField(
            model_name='malnutrition',
            name='d31_stress_illness_hospitalization',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='31. Nos últimos 3 meses passou por algum estresse psicológico, doença aguda ou internações?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_analyse',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='8. É perceptível uma visão mais negativa da velhice]?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_negative_points',
            field=models.TextField(blank=True, null=True, verbose_name='8. Aspectos Negativos do Envelhecimento'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_positive_points',
            field=models.TextField(blank=True, null=True, verbose_name='8. Aspectos Positivo do Envelhecimento'),
        ),
    ]
