# Generated by Django 2.2.6 on 2020-09-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0005_auto_20200911_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falls',
            name='max_score_falls',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='falls',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
