# Generated by Django 2.2.7 on 2019-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0005_auto_20191208_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='interviewed',
            field=models.CharField(choices=[['Participante', 'Participante'], ['Cuidador Formal', 'Cuidador Formal'], ['Familiar', 'Familiar']], max_length=20, null=True, verbose_name='Pessoa entrevistada:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='service',
            field=models.CharField(max_length=60, null=True, verbose_name='Serviço/instituição'),
        ),
    ]
