# Generated by Django 2.2.4 on 2019-09-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0005_auto_20190920_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='comments',
            field=models.TextField(verbose_name='Observações sobre o bloco Psicológico'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='max_score',
            field=models.IntegerField(default=14),
        ),
    ]
