# Generated by Django 2.2.4 on 2019-09-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_section', '0001_initial'),
        ('health_section', '0001_initial'),
        ('page_section', '0006_auto_20190920_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agingaspects',
            options={'ordering': ['id'], 'verbose_name': 'Aspectos relativos ao envelhecimento'},
        ),
        migrations.AlterModelOptions(
            name='cognitiondeficit',
            options={'ordering': ['id'], 'verbose_name': 'Déficit Cognitivo'},
        ),
        migrations.AlterModelOptions(
            name='depression',
            options={'ordering': ['id'], 'verbose_name': 'Depressão'},
        ),
        migrations.AlterModelOptions(
            name='negativeattitudesaging',
            options={'ordering': ['id'], 'verbose_name': 'Atitudes Negativas em Relação ao Processo de Envelhecimento'},
        ),
        migrations.AlterModelOptions(
            name='psychologicalaspects',
            options={'ordering': ['id'], 'verbose_name': 'Relacionados a Aspectos Psicológicos'},
        ),
        migrations.RenameField(
            model_name='biologicalaspects',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='cardiovascularfactors',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='environmentalproblems',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='functionaldisability',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='lowsocialsupport',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='malnutrition',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='misusemedications',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='sensorydeficit',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='violence',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q33DCVFamiliarHistory',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q34Hypertension',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q35UncontrolledDiabetes',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q35UnknownValueGlycemia',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q36Cholesterol',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q36UnknownValueCT_HDL',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q37Smoker',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q38Practice150MinutesExercises',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q39HealthyEating',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q40AlcoholIngestedLastWeek',
        ),
        migrations.RemoveField(
            model_name='cardiovascularfactors',
            name='q41BMI_Obesity',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='Q66HandrailOnStairs',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q63EstableFurniture',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q64LooseObjectsCarpets',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q65SlipperyFloor',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q67LightedStairs',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q68SuitableStairsSteps',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q69NonSlipperyCarpet',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q70GetOnStool',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q71TurnLightsOff',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q72SafeShoes',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q73ManicureSidewalks',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q74PublicTransportAccess',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q75CommerceAccess',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q76EasePlasewalking',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q77FunAccess',
        ),
        migrations.RemoveField(
            model_name='environmentalproblems',
            name='q78Safety',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q100PriorAVE',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q101PsychotropicMedicationsUse',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q102HasDiseases',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q87FallsLastYear',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q88AmountFallsLastYear',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q89FracturesDueToFalls',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q89FracturesList',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q90Strength_MMII',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q91Equilibrium',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q92OlderThan75',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q93Female',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q94CognitiveAlterations',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q95AVDsCommitment',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q96VisualDeficit',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q97DomesticRisks',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q98BehaviorRisk',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='q99Inactivity',
        ),
        migrations.RemoveField(
            model_name='functionaldisability',
            name='q20ToShop',
        ),
        migrations.RemoveField(
            model_name='functionaldisability',
            name='q21UseTransport',
        ),
        migrations.RemoveField(
            model_name='functionaldisability',
            name='q22ToCook',
        ),
        migrations.RemoveField(
            model_name='functionaldisability',
            name='q24DressUp',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q53Father',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q54Brothers',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q54Children',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q54GranChildren',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q54Mother',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q54Spouse',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q55MeetFamilyFriends',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q56ParticipateFamilyDecisions',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q57SatisfiedFamilyRelationship',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q58HelpedIfNeedMoney',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q59SomeoneHelpsIfNeed',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q60SomeoneToHaveFun',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q61ParticipateSocialEvents',
        ),
        migrations.RemoveField(
            model_name='lowsocialsupport',
            name='q62RegularyHealtServices',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d26YourselfMalnourished',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d27ChewingMouthProblems',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d28Less3MealDaily',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d29DecreasesAmountFood',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d30LostWeightNoReason',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d30LostWeightNoReasonAmount',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='d31StressIllnessHospitalization',
        ),
        migrations.RemoveField(
            model_name='malnutrition',
            name='q32BMI_Less22',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q42DiseasesLast5Years',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q43HealthProblems',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q44AmountDiagnostics',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q45Medicines',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q46MedicinesIncrease',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q47KnowMedicines',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q48MedicationsPrecribed',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q49MedicineMedicalAdvice',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q50AlreadyStoppedMedicines',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q51SelfMedication',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q52InappropriateMedication',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q53RiskAdverseReaction',
        ),
        migrations.RemoveField(
            model_name='sensorydeficit',
            name='q15VisionProblems',
        ),
        migrations.RemoveField(
            model_name='sensorydeficit',
            name='q16HearingProblems',
        ),
        migrations.RemoveField(
            model_name='sensorydeficit',
            name='q17TasteProblems',
        ),
        migrations.RemoveField(
            model_name='sensorydeficit',
            name='q18SensesProblems',
        ),
        migrations.RemoveField(
            model_name='sensorydeficit',
            name='q19InteractionProblems',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q79AfraidClosePerson',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q80FeelsAbandoned',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q81Forced',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q82Assauteld',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q83InNeed',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q84SomeoneUsedMoney',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q85TouchedWithoutPermission',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='q86DontTakeCareHealth',
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q33_dcv_familiar_history',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='33. O(A) senhor(a) tem histórico familiar (1º grau) de DCV (infarto, derrama e/ou angina) ?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q34_hypertension',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='34. O(a) senhor(a) tem hipertensão arterial descontrolada? [Pontuar como sim quando PA auto referida for                    superior a 140/90 mmHg ou caso o(a) idoso(a) não saiba informar.]'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q34_hypertension_unknow',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Desconhece os valores da PA?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q35_uncontrolled_diabetes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='35. O(A) senhor(a) tem diabetes? Se sim, está descontrolada? [Pontuar como sim quando glicemia em jejum            verificada em último exame for superior a 100 mg/dL, respectivamente, ou caso o(a) idoso(a) não saiba informar].'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q35_unknown_value_glycemia',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Desconhece os valores de glicemia?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q36_cholesterol',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='36. O(A) senhor(a) tem colesterol alterado? [Pontuar como sim quando CT e HDL forem verificados em último                    exame como superior a 200 mg/dL e 60mg/dL, respectivamente, ou caso o(a) idoso(a) não saiba informar].'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q36_unknown_value_ct_hdl',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Desconhece os valores de CT e HDL?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q37_smoker',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='37. O(A) senhor(a) fuma ou é ex-fumante?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q38_practice_150_minutes_exercises',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='38. O(A) senhor(a) pratica mais de 150 minutos de exercícios físicos por semana?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q39_healthy_eating',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='39. O(A) senhor(a) considera que sua alimentação é saudável?'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q40_alcohol_Ingested_last_week',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='40. Na última semana, o(a) senhor(a) ingeriu bebidas alcoólicas? Assinale a resposta equivalente, considerando as seguintes                    referências] Homens: Mais do que 14 doses de destilado (350 ml), 7 taças de vinho (2 litros) ou 14 latas                   de cerveja (5 litros) Mulheres: Mais do que 7 doses de destilado (175 ml), 3 e ½ taças de vinho (1 litro)                   ou 7 latas de cerveja (2,5 litros)'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q40_alcohol_Ingested_last_week_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drinks_section.IngestedDrinks', verbose_name='Quantidade de Alcool Ingerido'),
        ),
        migrations.AddField(
            model_name='cardiovascularfactors',
            name='q41_bmi_obesity',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='41. IMC para obesidade: ≥27 Kg/m2 [Verificar na questão 18]'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q63_estable_furniture',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='63. Na casa do(a) senhor(a):[Ambiente interno] Os móveis são estáveis?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q64_loose_objects_carpets',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='64. Na casa do(a) senhor(a):[Ambiente interno] Há objetos e/ou tapetes soltos nas áreas de circulação?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q65_slippery_floor',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='65. Na casa do(a) senhor(a):[Ambiente interno] O piso é escorregadio (ex. encerado, molhado)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q66_handrail_on_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='66. Na casa do(a) senhor(a):[Ambiente interno] As escadas possuem corrimão em ambos os lados?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q67_lighted_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='67. Na casa do(a) senhor(a):[Ambiente interno] As escadas/ degraus são iluminados adequadamente'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q68_suitable_stairs_steps',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='68. Na casa do(a) senhor(a):[Ambiente interno] Os degraus são adequados (tamanho, rebordos, largura e                    padronagem, etc)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q69_non_slippery_carpet',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='69. Na casa do(a) senhor(a):[Ambiente interno] Há tapetes antiderrapantes (fora e dentro box)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q70_get_on_stool',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='70. O(A) senhor(a) costuma: [Comportamento de risco] Subir em banquetas ou cadeiras para alcançar                    objetos altos?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q71_turn_lights_off',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='71. O(A) senhor(a) costuma: [Comportamento de risco] Deixa as luzes apagadas quando se levanta à noite'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q72_safe_shoes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='72. O(A) senhor(a) costuma: [Comportamento de risco] Utiliza calçados seguros e adequados (solado                    antiderrapante, bem ajustados e firmes no pé, sem saltos, etc)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q73_manicure_sidewalks',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='73. O(A) senhor(a) está satisfeito com [Ambiente externo] As calçadas do seu bairro são bem cuidadas                    (pavimentadas, lisas e sem buracos)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q74_public_transport_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='74. O(A) senhor(a) está satisfeito com [Ambiente interno] O acesso ao transporte público no seu bairro?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q75_commerce_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='75. O(A) senhor(a) está satisfeito com [Ambiente interno] O acesso ao comércio no seu bairro?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q76_ease_plasewalking',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='76. O(A) senhor(a) está satisfeito com [Ambiente interno] A facilidade e prazer em andar (a pé/ com                    cadeira de rodas/bengala/andador) no seu bairro?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q77_fun_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='77. O(A) senhor(a) está satisfeito com [Ambiente interno]  O acesso à diversão no seu bairro (restaurantes,                   cinema, clubes, etc.)?'),
        ),
        migrations.AddField(
            model_name='environmentalproblems',
            name='q78_safety',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='78. O(A) senhor(a) está satisfeito com [Ambiente interno]  A segurança quanto à ameaça da criminalidade no                   seu bairro?'),
        ),
        migrations.AddField(
            model_name='falls',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q100_prior_ave',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='100. Acidente Vascular Encefálico prévio [Ver questão 42]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q101_psychotropic_medications_use',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='101. Faz uso de medicações psicotrópicas, em especial benzodiazepínicos, OU uso contínuo de 5 ou mais                     medicações (polifarmácia) [Ver questão 45]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q102_has_diseases',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='102. Apresenta alguma das doenças a seguir: hipertensão tontura/ vertigem, Parkinson, amputação de                     membros inferiores, convulsões, artrite, osteoporose, incontinência, diabetes, neuropatia, hipotensão                     postural [Ver questões 42 e 43]__________________________'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q87_amount_falls_last_year',
            field=models.IntegerField(default=1, verbose_name='Se sofreu quedas, quantas? ______ [Se não, pontue também a resposta “não” na próxima questão e vá                       para a questão 90] [Se não, pule as próximas duas questões].'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='falls',
            name='q87_falls_last_year',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='87. O(A) senhor(a) sofreu alguma queda nos últimos 12 meses?'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q88_fractures_due_to_falls',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='88. O(A) senhor(a) sofreu alguma fratura decorrente destas quedas?'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q88_fractures_due_to_falls_list',
            field=models.TextField(default=1, verbose_name='Se sim, quais?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='falls',
            name='q89_fractures_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_section.Fractures', verbose_name='89. O que o(a) senhor(a) estava fazendo quando sofreu essa(s) queda(s)? [Investigar atividade realizada,                    local, horário do dia, tipo de calçado, riscos ambientais etc]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q90_strength_mmii',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='90. [Avaliação de força de MMII] – Peça ao(a) idoso(a) para levantar-se de uma cadeira sem ajuda. Assinale                    ao lado se o(a) idoso(a) conseguiu realizar a tarefa.'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q91_equilibrium',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='91. [Avaliação de equilíbrio] Peça ao(a) idoso(a) para permanecer em pé em uma única perna, sem apoio dos                   membros superiores, durante 5 segundos. Assinale ao lado se o(a) idoso(a) consegue realizar a tarefa.'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q92_older_than75',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='92. Idade >75 anos [Ver em dados de identificação]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q93_female',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='93. Gênero feminino [Ver em dados de identificação]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q94_cognitive_alterations',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='94. Alterações cognitivas [Pontuação negativa em Fluência Verbal em Funções Cognitivas]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q95_av_ds_commitment',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='95. Comprometimento AVDs [Pontuação > 4 em Capacidade Funcional]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q96_visual_deficit',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='96. Déficit Visual [Ver questão 15]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q97_domestic_risks',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='97. Riscos domésticos [Ver questões 63 a 69]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q98_behavior_risk',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='98. Riscos comportamentais [Ver questões 70 a 72]'),
        ),
        migrations.AddField(
            model_name='falls',
            name='q99_inactivity',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='99. Inatividade [Ver questão 38]'),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='q20_to_shop',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='20. O(A) senhor(a) necessita de ajuda para Fazer compras?'),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='q21_use_transport',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='21. O(A) senhor(a) necessita de ajuda para Usar meios de transporte?'),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='q22_to_cook',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='22. O(A) senhor(a) necessita de ajuda para Preparar a própria comida?'),
        ),
        migrations.AddField(
            model_name='functionaldisability',
            name='q24_dress_up',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='24. O(A) senhor(a) necessita de ajuda para Vestir-se?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_brothers',
            field=models.IntegerField(default=1, verbose_name='O(A) senhor(a) tem quantos irmãos?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_children',
            field=models.IntegerField(default=1, verbose_name='O(A) senhor(a) tem quantos filhos?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_father',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='O(A) senhor(a) tem: Pai?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_gran_children',
            field=models.IntegerField(default=1, verbose_name='O(A) senhor(a) tem quantos netos?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_mother',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='O(A) senhor(a) tem: Mãe?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q54_spouse',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='O(A) senhor(a) tem: cônjuge?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q55_meet_family_friends',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='55. O(A) senhor(a) encontra familiares e/ou amigos com frequência?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q56_participate_family_decisions',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='56. O(A) senhor(a) participa de decisões importantes da sua família?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q57_satisfied_family_relationship',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='57. O(A) senhor(a) se sente satisfeito(a) com o relacionamento afetivo que tem com os seus familiares?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q58_helped_if_need_money',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='58. O(A) senhor(a) tem ajuda de alguém se precisar de dinheiro?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q59_someone_helps_if_need',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='59. O(A) senhor(a) pode contar com alguém para ajuda-lo(a) a resolver problemas?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q60_someone_to_have_fun',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='60. O(A) senhor(a) tem pessoas com quem possa se divertir e relaxar?'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q61_participate_social_events',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='61. O(A) senhor(a) participa de eventos sócio-culturais, tais como: peças de teatro, cinema, universidade                   aberta a terceira idade, centro de convivência, festas, ligados à religião, etc).'),
        ),
        migrations.AddField(
            model_name='lowsocialsupport',
            name='q62_regulary_healt_services',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='62. O(A) senhor(a) é acompanhado regularmente por serviços de saúde?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d26_yourself_malnourished',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='26. O(A) senhor(a) que está desnutrido?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d27_chewing_mouth_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='27. O(A) senhor(a) tem lesões na região bucal ou algum outro problema que provoque dificuldades de                    mastigação?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d28_less3_meal_daily',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='28. O(A) senhor(a) faz menos de três refeições por dia?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d29_decreases_amount_food',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='29. Nos últimos 3 meses, o(a) senhor(a) Diminuiu sua ingesta alimentar sem motivo?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d30_lost_weight_no_reason',
            field=models.CharField(choices=[['Não', 'Não'], ['Não sabe', 'Não sabe'], ['Mais de 3 KG', 'Mais de 3 Kg'], ['Entre 1 e 3 KG', 'Entre 1 e 3 KG']], default='N', max_length=1, verbose_name='30. Nos últimos 3 meses, o(a) senhor(a) Perdeu peso sem motivo aparente?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='d31_stress_illness_hospitalization',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='31. Passou por algum estresse psicológico, doença aguda ou internações?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='malnutrition',
            name='q32_bmi_less22',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='32. Índice de Massa Corporal (peso[kg]/ estatura[m2]) =  kg/m2) igual ou menor que 22 kg/m2?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.Diseases', verbose_name='42. Nos últimos 5 anos, algum médico ou outro profissional de saúde já disse que o(a) senhor(a) tem:'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.HealthProblems', verbose_name='43. O(A) senhor(a) tem algum dos seguintes problemas de saúde:'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q44_amount_diagnostics',
            field=models.IntegerField(default=1, verbose_name='44. Quantidade de diagnósticos (doenças):'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q45_medicines',
            field=models.ManyToManyField(blank=True, related_name='patients', to='health_section.Medicines', verbose_name='45. [Solicitar as bulas dos medicamentos utilizados pelo(a) senhor(a) e fazer registro legível dos                    respectivos nomes e classes terapêuticas]'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q46_medicines_increase',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='46. Nos últimos 6 meses, a quantidade de medicamentos que o(a) senhor(a) toma aumentou muito?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q47_know_medicines',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='47. O(A) senhor(a) sabe para que serve todos os seus medicamentos?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q48_medications_prescribed',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='48. Os medicamentos que o(a) senhor(a) faz uso foram prescritos por médicos diferentes?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q49_medicine_medical_advice',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='49. O(A) senhor(a) toma os medicamentos de acordo com as orientações médicas?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q50_already_stopped_medicines',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='50. O(A) senhor(a) alguma vez já deixou de tomar os medicamentos?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q51_self_medication',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='51. O(A) senhor(a) tem o costume de tomar remédios por conta própria?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q52_inappropriate_medication',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='52. Verificar na lista de medicamentos potencialmente inapropriados para idosos brasileiros                   (anexada ao PAGe) se o(a) idoso(a) toma algum dos medicamentos citados na mesma. [Caso sim, pontue ao lado                   e os deixe destacados na lista]'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q53_risk_adverse_reaction',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='53. Cálculo do risco para reações adversas. [Verifique as respostas das questões 30 e 38. Circule e cruze                   as informações na tabela abaixo. Em seguida, verifique os registros da questão 31 e assinale ao lado se                    o(a) idoso(a) utiliza uma quantidade de medicamentos superior ao valor indicado na tabela] '),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='q15_vision_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='15. O(A) senhor(a) tem problemas de visão?'),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='q16_hearing_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='16. O(A) senhor(a) tem dificuldade de ouvir o que as pessoas falam?'),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='q17_taste_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='17. O(A) senhor(a) tem dificuldade para sentir o sabor dos alimentos?'),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='q18_senses_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='18. O(A) senhor(a) considera ruim o funcionamento dos seus sentidos?'),
        ),
        migrations.AddField(
            model_name='sensorydeficit',
            name='q19_interaction_problems',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='19. O(A) senhor(a) considera que o funcionamento dos seus sentidos afeta sua capacidade de interagir com                    outras pessoas?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='need_investigation',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='Necessita Investigação?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q79_afraid_close_person',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='79. O(A) senhor(a) tem medo de alguém próximo/do seu convívio?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q80_feels_abandoned',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='80. O(A) senhor(a) se sente só ou abandonado?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q81_forced',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='81. Alguém tem falado com o(a) senhor(a) de forma que se sinta constrangido(a) ou desrespeitado(a)?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q82_assauteld',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='82. Alguém tem agredido o(a) senhor(a) fisicamente?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q83_in_need',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='83. O(A) senhor(a) tem passado necessidade de roupas, alimentação, medicamentos ou outras?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q84_someone_used_money',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='84. Alguém tem usado o dinheiro do(a) senhor(a) sem a sua autorização?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q85_touched_without_permission',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='85. Alguém do seu convívio já tocou o corpo do(a) senhor(a) sem o seu consentimento?'),
        ),
        migrations.AddField(
            model_name='violence',
            name='q86_dont_take_care_health',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='86. O(A) senhor(a) está deixando de cuidar da sua própria saúde e/ou segurança?'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q2_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='2. Memória'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q3_language_function_attention',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='3. Linguagem, função executiva e atenção'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q4_visospatial_ability_score',
            field=models.IntegerField(default=0, verbose_name='4. Habilidade visuoespacial - Pontuação:'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q5_praxia',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='5. Praxia'),
        ),
        migrations.AlterField(
            model_name='cognitiondeficit',
            name='q6_memory_test',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='6. Memória'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q11_stopped_doing_things',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='11. O(A) senhor(a) abandonou muitas das coisas que fazia ou gostava de fazer?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q14_concentration_problem',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='14. O(A) senhor(a) tem dificuldade em se concentrar?'),
        ),
        migrations.AlterField(
            model_name='depression',
            name='q9_satisfied_with_life',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='9. De modo geral o(a) senhor(a) está satisfeito com a vida?'),
        ),
        migrations.AlterField(
            model_name='functionaldisability',
            name='q23UseTelephone',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='23. O(A) senhor(a) necessita de ajuda para Usar o telefone?'),
        ),
        migrations.AlterField(
            model_name='functionaldisability',
            name='q25TakeShower',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='25. O(A) senhor(a) necessita de ajuda para Tomar banho?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q7_age_self_perception',
            field=models.IntegerField(blank=True, null=True, verbose_name='7. Que idade o(a) senhor(a) sente ter?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q7_age_self_perception_analyze',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='O(a) idoso(a) sente-se mais velho do que realmente é?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q7_age_self_perception_why',
            field=models.TextField(blank=True, null=True, verbose_name='Por quê?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_analyse',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='É perceptível uma visão mais negativa da velhice]?'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_negative_points',
            field=models.ManyToManyField(blank=True, related_name='NegativePoints', to='page_section.AgingAspects', verbose_name='Aspectos Negativos do Envelhecimento'),
        ),
        migrations.AlterField(
            model_name='negativeattitudesaging',
            name='q8_aging_positive_points',
            field=models.ManyToManyField(blank=True, related_name='PositivePoints', to='page_section.AgingAspects', verbose_name='Aspectos Positivo do Envelhecimento'),
        ),
    ]
