# Generated by Django 2.2.6 on 2020-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0006_auto_20200911_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiondeficit',
            name='xscore',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
