# Generated by Django 2.2.7 on 2019-12-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0006_auto_20191222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='avaliation_date',
            field=models.DateField(null=True, verbose_name='Data da Avaliação'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
