# Generated by Django 2.2.4 on 2019-09-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0007_auto_20190921_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agingaspects',
            options={'ordering': ['id'], 'verbose_name': 'Aspectos relativos ao envelhecimento', 'verbose_name_plural': 'Aspectos relativos ao envelhecimento'},
        ),
        migrations.AlterModelOptions(
            name='biologicalaspects',
            options={'ordering': ['id'], 'verbose_name': 'Relacionados a Aspectos Biológicos', 'verbose_name_plural': 'Relacionados a Aspectos Biológicos'},
        ),
        migrations.AlterModelOptions(
            name='cardiovascularfactors',
            options={'ordering': ['id'], 'verbose_name': 'Doenças Cardiovasculares (DCV)', 'verbose_name_plural': 'Doenças Cardiovasculares (DCV)'},
        ),
        migrations.AlterModelOptions(
            name='cognitiondeficit',
            options={'ordering': ['id'], 'verbose_name': 'Déficit Cognitivo', 'verbose_name_plural': 'Déficit Cognitivo'},
        ),
        migrations.AlterModelOptions(
            name='demandmap',
            options={'ordering': ['id'], 'verbose_name': 'Mapa das Demandas', 'verbose_name_plural': 'Mapa das Demandas'},
        ),
        migrations.AlterModelOptions(
            name='depression',
            options={'ordering': ['id'], 'verbose_name': 'Depressão', 'verbose_name_plural': 'Depressão'},
        ),
        migrations.AlterModelOptions(
            name='environmentalproblems',
            options={'ordering': ['id'], 'verbose_name': 'Problemas Ambientais', 'verbose_name_plural': 'Problemas Ambientais'},
        ),
        migrations.AlterModelOptions(
            name='falls',
            options={'ordering': ['id'], 'verbose_name': 'Quedas', 'verbose_name_plural': 'Quedas'},
        ),
        migrations.AlterModelOptions(
            name='functionaldisability',
            options={'ordering': ['id'], 'verbose_name': 'Incapacidade Funcional', 'verbose_name_plural': 'Incapacidade Funcional'},
        ),
        migrations.AlterModelOptions(
            name='lowsocialsupport',
            options={'ordering': ['id'], 'verbose_name': 'Baixo Suporte Social', 'verbose_name_plural': 'Baixo Suporte Social'},
        ),
        migrations.AlterModelOptions(
            name='malnutrition',
            options={'ordering': ['id'], 'verbose_name': 'Desnutrição', 'verbose_name_plural': 'Desnutrição'},
        ),
        migrations.AlterModelOptions(
            name='misusemedications',
            options={'ordering': ['id'], 'verbose_name': 'Uso Inadequado de Medicamentos', 'verbose_name_plural': 'Uso Inadequado de Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='multidisciplinarydomain',
            options={'ordering': ['id'], 'verbose_name': 'Domínio Multidimensional', 'verbose_name_plural': 'Domínio Multidimensional'},
        ),
        migrations.AlterModelOptions(
            name='negativeattitudesaging',
            options={'ordering': ['id'], 'verbose_name': 'Atitudes Negativas em Relação ao Processo de Envelhecimento', 'verbose_name_plural': 'Atitudes Negativas em Relação ao Processo de Envelhecimento'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id'], 'verbose_name': 'Page', 'verbose_name_plural': 'Page'},
        ),
        migrations.AlterModelOptions(
            name='psychologicalaspects',
            options={'ordering': ['id'], 'verbose_name': 'Relacionados a Aspectos Psicológicos', 'verbose_name_plural': 'Relacionados a Aspectos Psicológicos'},
        ),
        migrations.AlterModelOptions(
            name='recommendedactivities',
            options={'ordering': ['id'], 'verbose_name': 'Atividades Recomendadas', 'verbose_name_plural': 'Atividades Recomendadas'},
        ),
        migrations.AlterModelOptions(
            name='sensorydeficit',
            options={'ordering': ['id'], 'verbose_name': 'Déficit Sensorial', 'verbose_name_plural': 'Déficit Sensorial'},
        ),
        migrations.AlterModelOptions(
            name='socialaspects',
            options={'ordering': ['id'], 'verbose_name': 'Relacionados a Aspectos Sociais', 'verbose_name_plural': 'Relacionados a Aspectos Sociais'},
        ),
        migrations.AlterModelOptions(
            name='violence',
            options={'ordering': ['id'], 'verbose_name': 'Violência', 'verbose_name_plural': 'Violência'},
        ),
        migrations.AlterField(
            model_name='biologicalaspects',
            name='comments',
            field=models.TextField(verbose_name='Observações Sobre o Bloco Biológico'),
        ),
        migrations.AlterField(
            model_name='biologicalaspects',
            name='max_score',
            field=models.IntegerField(default=36, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='max_score',
            field=models.IntegerField(default=9, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='dm3_unmet_demands',
            field=models.TextField(null=True, verbose_name='O(a) idoso(a) apresenta outras demandas não contempladas no mapa? Se sim, especificar:'),
        ),
        migrations.AlterField(
            model_name='demandmap',
            name='gerontologist_assessment',
            field=models.TextField(null=True, verbose_name='Avaliação do Gerontólogo'),
        ),
        migrations.AlterField(
            model_name='functionaldisability',
            name='max_score',
            field=models.IntegerField(default=6, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='malnutrition',
            name='max_score',
            field=models.IntegerField(default=6, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='misusemedications',
            name='max_score',
            field=models.IntegerField(default=9, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='multidisciplinarydomain',
            name='comments',
            field=models.TextField(verbose_name='Observações Sobre o Bloco Multidimensional'),
        ),
        migrations.AlterField(
            model_name='multidisciplinarydomain',
            name='maxScore',
            field=models.IntegerField(default=8, verbose_name='Pontuação Máxima'),
        ),
        migrations.RemoveField(
            model_name='negativeattitudesaging',
            name='q8_aging_negative_points',
        ),
        migrations.AddField(
            model_name='negativeattitudesaging',
            name='q8_aging_negative_points',
            field=models.TextField(blank=True, null=True, verbose_name='Aspectos Negativos do Envelhecimento'),
        ),
        migrations.RemoveField(
            model_name='negativeattitudesaging',
            name='q8_aging_positive_points',
        ),
        migrations.AddField(
            model_name='negativeattitudesaging',
            name='q8_aging_positive_points',
            field=models.TextField(blank=True, null=True, verbose_name='Aspectos Positivo do Envelhecimento'),
        ),
        migrations.AlterField(
            model_name='page',
            name='biologicalAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.BiologicalAspects', verbose_name='Relacionados a Aspectos Biológicos'),
        ),
        migrations.AlterField(
            model_name='page',
            name='demandMap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.DemandMap', verbose_name='Mapa de Demandas'),
        ),
        migrations.AlterField(
            model_name='page',
            name='expertAssessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment_section.ExpertAssessment', verbose_name='Planejamento das Ações'),
        ),
        migrations.AlterField(
            model_name='page',
            name='gerontologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experts_section.Gerontologist', verbose_name='Gerontologista Resposável'),
        ),
        migrations.AlterField(
            model_name='page',
            name='multidisciplinaryDomain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.MultidisciplinaryDomain', verbose_name='Domínio Multidisciplinar'),
        ),
        migrations.AlterField(
            model_name='page',
            name='psychologicalAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.PsychologicalAspects', verbose_name='Relacionados a Aspectos Psicológicos'),
        ),
        migrations.AlterField(
            model_name='page',
            name='socialAspects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.SocialAspects', verbose_name='Relacionados a Aspectos Sociais'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='cognition_deficit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.CognitionDeficit', verbose_name='Déficit Cognitivo'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='depression',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.Depression', verbose_name='Depressão'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='max_score',
            field=models.IntegerField(default=14, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='negative_attitudes_aging',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='page_section.NegativeAttitudesAging', verbose_name='Atitude Negativa em Relação ao Envelhecimento'),
        ),
        migrations.AlterField(
            model_name='socialaspects',
            name='comments',
            field=models.TextField(verbose_name='Observações Sobre o Bloco Social'),
        ),
        migrations.AlterField(
            model_name='socialaspects',
            name='maxScore',
            field=models.IntegerField(default=32, verbose_name='Pontuação Máxima'),
        ),
    ]
