# Generated by Django 2.2.7 on 2019-12-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0007_auto_20191222_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalaspects',
            name='comments_psico',
            field=models.TextField(null=True, verbose_name='Observações sobre o bloco Psicológico'),
        ),
    ]
