# Generated by Django 2.2.4 on 2019-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0008_auto_20190923_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiovascularfactors',
            name='q40_alcohol_Ingested_last_week_amount',
            field=models.TextField(blank=True, null=True, verbose_name='Quantidade de Alcool Ingerido'),
        ),
    ]
