# Generated by Django 2.2.4 on 2019-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0009_auto_20190923_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years',
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q43_health_problems',
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_a',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='a) Doença do coração (angina, infarto ou ataque cardíaco)?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_b',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='b) Pressão alta/ hipertensão?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_c',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='c) Derrame/AVC/Isquemia?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_d',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='d) Diabetes Mellitus?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_e',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='e) Tumor maligno/ Câncer?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_f',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='f) Asma/Bronquite/Enfisema?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_g',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='g) Osteoporose?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_h',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='h) Reumatismo?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_i',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='i) Tendinite?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_j',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='j) Problemas de circulação?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_k',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='k) Depressão?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q42_diseases_last_5_years_l',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='l)Outra?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_a',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='a) Dor de cabeça?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_b',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='b) Dor nas costas ou em outra parte do corpo?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_c',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='c) Alergia?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_d',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='d) Problema emocional?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_e',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='e) Tontura?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_f',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='f) Dificuldades para dormir?'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_g',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='g) Incontinência urinária/perda de urina'),
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q43_health_problems_h',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='h)Outro?_______________________________________'),
        ),
        migrations.RemoveField(
            model_name='misusemedications',
            name='q45_medicines',
        ),
        migrations.AddField(
            model_name='misusemedications',
            name='q45_medicines',
            field=models.TextField(blank=True, null=True, verbose_name='45. [Solicitar as bulas dos medicamentos utilizados pelo(a) senhor(a) e fazer registro legível dos                    respectivos nomes e classes terapêuticas]'),
        ),
    ]
