# Generated by Django 2.2.4 on 2019-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0010_auto_20190923_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falls',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q64_loose_objects_carpets',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='64. Na casa do(a) senhor(a): Há objetos e/ou tapetes soltos nas áreas de circulação?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q65_slippery_floor',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='65. Na casa do(a) senhor(a): O piso é escorregadio (ex. encerado, molhado)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q66_handrail_on_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='66. Na casa do(a) senhor(a): As escadas possuem corrimão em ambos os lados?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q67_lighted_stairs',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='67. Na casa do(a) senhor(a): As escadas/ degraus são iluminados adequadamente'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q68_suitable_stairs_steps',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='68. Na casa do(a) senhor(a): Os degraus são adequados (tamanho, rebordos, largura e                    padronagem, etc)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q69_non_slippery_carpet',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='69. Na casa do(a) senhor(a): Há tapetes antiderrapantes (fora e dentro box)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q70_get_on_stool',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='70. O(A) senhor(a) costuma: Subir em banquetas ou cadeiras para alcançar                    objetos altos?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q71_turn_lights_off',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='71. O(A) senhor(a) costuma:  Deixa as luzes apagadas quando se levanta à noite'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q72_safe_shoes',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='72. O(A) senhor(a) costuma: Utiliza calçados seguros e adequados (solado                    antiderrapante, bem ajustados e firmes no pé, sem saltos, etc)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q73_manicure_sidewalks',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='73. O(A) senhor(a) está satisfeito com As calçadas do seu bairro são bem cuidadas                    (pavimentadas, lisas e sem buracos)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q74_public_transport_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='74. O(A) senhor(a) está satisfeito com o acesso ao transporte público no seu bairro?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q75_commerce_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='75. O(A) senhor(a) está satisfeito com o acesso ao comércio no seu bairro?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q76_ease_plasewalking',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='76. O(A) senhor(a) está satisfeito com a facilidade e prazer em andar (a pé/ com                    cadeira de rodas/bengala/andador) no seu bairro?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q77_fun_access',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='77. O(A) senhor(a) está satisfeito com o acesso à diversão no seu bairro (restaurantes,                   cinema, clubes, etc.)?'),
        ),
        migrations.AlterField(
            model_name='environmentalproblems',
            name='q78_safety',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='78. O(A) senhor(a) está satisfeito com a segurança quanto à ameaça da criminalidade no                   seu bairro?'),
        ),
        migrations.AlterField(
            model_name='falls',
            name='q102_has_diseases',
            field=models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], default='N', max_length=1, verbose_name='102. Apresenta alguma das doenças a seguir: hipertensão tontura/ vertigem, Parkinson, amputação de                     membros inferiores, convulsões, artrite, osteoporose, incontinência, diabetes, neuropatia, hipotensão                     postural [Ver questões 42 e 43]'),
        ),
        migrations.AlterField(
            model_name='falls',
            name='q87_amount_falls_last_year',
            field=models.IntegerField(verbose_name='Se sofreu quedas, quantas?  [Se não, pontue também a resposta “não” na próxima questão e vá                       para a questão 90] [Se não, pule as próximas duas questões].'),
        ),
        migrations.AlterField(
            model_name='misusemedications',
            name='q43_health_problems_h',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='h)Outro?'),
        ),
    ]
