# Generated by Django 2.2.4 on 2019-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_section', '0011_auto_20190923_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falls',
            name='q89_fractures_list',
            field=models.TextField(blank=True, null=True, verbose_name='89. O que o(a) senhor(a) estava fazendo quando sofreu essa(s) queda(s)? [Investigar atividade realizada,                    local, horário do dia, tipo de calçado, riscos ambientais etc]'),
        ),
    ]
