# Generated by Django 3.1.6 on 2021-03-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependentConditions', models.CharField(default='MISSED GREATER_THAN 0', max_length=150)),
                ('action', models.CharField(default='POSTPONE_EVENT MINUTES 60', max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(default='active', max_length=50)),
                ('color', models.CharField(blank=True, default='#0F5394', max_length=50, null=True)),
                ('activate', models.CharField(default='y', max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerType', models.CharField(default='time', max_length=10)),
                ('triggerCondition', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('timeOut', models.IntegerField(default=1800000)),
            ],
            options={
                'verbose_name': 'EventTrigger',
                'verbose_name_plural': 'EventTriggers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('urlForDataFile', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MediaPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='image', max_length=10)),
                ('mediaUrl', models.URLField()),
                ('autoPlay', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonEsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('profilePhotoUrl', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('activate', models.CharField(default='y', max_length=1)),
                ('updateDate', models.CharField(blank=True, default='1616105579000', max_length=50)),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorType', models.IntegerField()),
                ('sensor', models.CharField(default='activity', max_length=20)),
                ('collector', models.CharField(default='smartwatch', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActiveEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esm_program_section.event')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('esm_program_section.event',),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='empty', max_length=10)),
                ('statement', models.CharField(max_length=800)),
                ('orderPosition', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
                ('activate', models.CharField(default='y', max_length=1)),
                ('mediaType', models.CharField(blank=True, default='image', max_length=10, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('appPackage', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.CharField(blank=True, max_length=100, null=True)),
                ('startFromNotification', models.BooleanField(default=False)),
                ('window_x', models.IntegerField(default=0, null=True)),
                ('window_y', models.IntegerField(default=0, null=True)),
                ('window_width', models.IntegerField(default=0, null=True)),
                ('window_height', models.IntegerField(default=0, null=True)),
                ('medias', models.ManyToManyField(blank=True, to='esm_program_section.MediaPresentation')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.activeevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EditorProgram',
            fields=[
                ('personesm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esm_program_section.personesm')),
                ('role', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('schooling', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=40, null=True)),
                ('observerContacts', models.ManyToManyField(blank=True, related_name='_editorprogram_observerContacts_+', to='esm_program_section.EditorProgram')),
            ],
            bases=('esm_program_section.personesm',),
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionType', models.CharField(default='c', max_length=1)),
                ('objectType', models.CharField(default='p', max_length=1)),
                ('actionDate', models.CharField(blank=True, default='1616105579000', max_length=50)),
                ('intervention_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.intervention')),
                ('program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.program')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.editorprogram')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.activeevent')),
            ],
        ),
    ]
