# Generated by Django 3.1.6 on 2021-03-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsEsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionType', models.CharField(default='c', max_length=1)),
                ('objectType', models.CharField(default='p', max_length=1)),
                ('actionDate', models.CharField(blank=True, default='1616106234000', max_length=50)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.editorprogram')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.activeevent')),
                ('intervention_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.intervention')),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616106234000', max_length=50),
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.AddField(
            model_name='actionsesm',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.program'),
        ),
    ]
