# Generated by Django 3.1.6 on 2021-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0003_auto_20210319_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorprogram',
            name='observerContacts',
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616160903000', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616160903000', max_length=50),
        ),
    ]
