# Generated by Django 3.1.6 on 2021-03-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0004_auto_20210319_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsesm',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='actionsesm',
            name='intervention_id',
        ),
        migrations.RemoveField(
            model_name='actionsesm',
            name='program_id',
        ),
        migrations.AddField(
            model_name='actionsesm',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616337797000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.editorprogram'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616337797000', max_length=50),
        ),
    ]
