# Generated by Django 3.1.6 on 2021-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0005_auto_20210321_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsesm',
            name='object_id',
        ),
        migrations.AddField(
            model_name='actionsesm',
            name='event_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='actionsesm',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='actionsesm',
            name='program_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616417607000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616417607000', max_length=50),
        ),
    ]
