# Generated by Django 3.1.6 on 2021-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0006_auto_20210322_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsesm',
            name='anterior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616418455000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616418455000', max_length=50),
        ),
    ]
