# Generated by Django 3.1.6 on 2021-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0007_auto_20210322_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616445504000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616445504000', max_length=50),
        ),
    ]
