# Generated by Django 3.1.6 on 2021-03-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0009_auto_20210322_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='event_ptr',
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616457014000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616457014000', max_length=50),
        ),
    ]
