# Generated by Django 3.1.6 on 2021-03-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0010_auto_20210322_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=100, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esm_program_section.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616457511000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616457511000', max_length=50),
        ),
    ]
