# Generated by Django 3.1.6 on 2021-03-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0011_auto_20210322_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='event',
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616458146000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616458146000', max_length=50),
        ),
        migrations.DeleteModel(
            name='ActiveEvent',
        ),
    ]
