# Generated by Django 3.1.6 on 2021-03-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0012_auto_20210323_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616458270000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616458270000', max_length=50),
        ),
        migrations.CreateModel(
            name='ActiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(default='active', max_length=50)),
                ('color', models.CharField(blank=True, default='#0F5394', max_length=50, null=True)),
                ('activate', models.CharField(default='y', max_length=1)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.program')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
