# Generated by Django 3.1.6 on 2021-03-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0013_auto_20210323_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.activeevent'),
        ),
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616506331000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616506331000', max_length=50),
        ),
    ]
