# Generated by Django 3.1.6 on 2021-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0014_auto_20210323_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsesm',
            name='actionDate',
            field=models.CharField(blank=True, default='1616590642000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='1616590642000', max_length=50),
        ),
    ]
