# Generated by Django 3.1.6 on 2021-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0017_auto_20210324_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='program',
        ),
    ]
