# Generated by Django 3.1.6 on 2021-03-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0018_auto_20210324_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='activate',
            field=models.CharField(default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='esm_program_section.program'),
        ),
    ]
