# Generated by Django 3.1.6 on 2021-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0019_auto_20210324_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='dom',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='durationBell',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='minute',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='qua',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='qui',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='sab',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='seg',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='sex',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='ter',
            field=models.CharField(default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='typeBell',
            field=models.CharField(default='NC', max_length=2, null=True),
        ),
    ]
