# Generated by Django 3.1.6 on 2021-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0021_auto_20210412_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='subType',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='orderPosition',
            field=models.IntegerField(default=1000000),
        ),
    ]
