# Generated by Django 3.1.6 on 2021-04-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0022_auto_20210413_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='appPackage',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='complexConditions',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='first',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='mediaType',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='next',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='obligatory',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='orderPosition',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='question',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='startFromNotification',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='subType',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='type',
        ),
    ]
