# Generated by Django 3.1.6 on 2021-04-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0023_auto_20210414_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='activate',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
