# Generated by Django 3.1.6 on 2021-04-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0024_intervention_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='statement',
            new_name='intervention',
        ),
    ]
