# Generated by Django 3.1.6 on 2021-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0025_auto_20210414_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='first',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activeevent',
            name='next',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
