# Generated by Django 3.1.6 on 2021-04-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0026_auto_20210415_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='window_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='window_width',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='window_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='window_y',
            new_name='y',
        ),
    ]
