# Generated by Django 3.1.6 on 2021-04-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm_program_section', '0027_auto_20210415_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='height',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='width',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='x',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='y',
        ),
    ]
