# Generated by Django 2.2.4 on 2019-09-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_section', '0001_initial'),
        ('activities_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedules', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=30)),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers3', to='activities_section.Activity')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers1', to='institution_section.Institution')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers2', to='institution_section.Location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedActivitiesOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('systemRating', models.IntegerField()),
                ('expertRating', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('expertConsideration', models.TextField()),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers4', to='recommender_section.Offers', verbose_name='Atividade Ofertada')),
            ],
            options={
                'verbose_name': 'Atividades Ofertadas Recomendadas',
                'verbose_name_plural': 'Atividades Ofertadas Recomendadas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('systemRating', models.IntegerField()),
                ('expertRating', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('expertConsideration', models.TextField()),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers5', to='activities_section.Activity', verbose_name='Atividades')),
            ],
            options={
                'verbose_name': 'Atividades Recomendadas',
                'verbose_name_plural': 'Atividades Recomendadas',
                'ordering': ['id'],
            },
        ),
    ]
