# Generated by Django 3.0.7 on 2020-08-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution_section', '0004_auto_20200818_1212'),
        ('recommender_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedactivitiesoffers',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers4', to='institution_section.Offers', verbose_name='Atividade Ofertada'),
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
