# Generated by Django 2.2.4 on 2019-08-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant_section', '0001_initial'),
        ('activities_section', '0001_initial'),
        ('institution_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedules', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=30)),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='activities_section.Activity')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='institution_section.Location')),
                ('participants', models.ManyToManyField(blank=True, related_name='offers', to='participant_section.Participant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='activities_section.Activity')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='review_section.Offer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='participant_section.Participant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
