# Generated by Django 2.2.4 on 2019-08-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities_section', '0001_initial'),
        ('institution_section', '0001_initial'),
        ('review_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedules', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=30)),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='activities_section.Activity')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='institution_section.Location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='review_section.Offers'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
