# Generated by Django 2.2.6 on 2020-02-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('benefit', models.ManyToManyField(blank=True, related_name='activities', to='activities_section.Benefit')),
                ('characteristic', models.ManyToManyField(blank=True, related_name='activities', to='activities_section.Characteristic')),
                ('restriction', models.ManyToManyField(blank=True, related_name='activities', to='activities_section.Restriction')),
                ('type', models.ManyToManyField(blank=True, related_name='activities', to='activities_section.Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
