# Generated by Django 2.2.7 on 2020-01-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities_section.Detail')),
            ],
            bases=('activities_section.detail',),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('benefit', models.ManyToManyField(related_name='activities', to='activities_section.Benefit')),
                ('characteristic', models.ManyToManyField(related_name='activities', to='activities_section.Characteristic')),
                ('restriction', models.ManyToManyField(related_name='activities', to='activities_section.Restriction')),
                ('type', models.ManyToManyField(related_name='activities', to='activities_section.Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
