# Generated by Django 2.2.6 on 2020-10-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='author',
        ),
    ]
