# Generated by Django 2.2.7 on 2020-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='benefit',
            field=models.ManyToManyField(null=True, related_name='activities', to='activities_section.Benefit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='characteristic',
            field=models.ManyToManyField(null=True, related_name='activities', to='activities_section.Characteristic'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='restriction',
            field=models.ManyToManyField(null=True, related_name='activities', to='activities_section.Restriction'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.ManyToManyField(null=True, related_name='activities', to='activities_section.Type'),
        ),
    ]
