# Generated by Django 2.2.6 on 2020-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_section', '0002_remove_activity_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='image',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='type_activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='general_activity_objective',
            field=models.TextField(null=True),
        ),
    ]
